### PR TITLE
optimize png images losslessly using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
8 images optimized using Google's zopflipng.
```
 docbook/Admin_Guide/en-US/images/mantis_logo.png      | Bin 35725 -> 19036 bytes
 docbook/Developers_Guide/en-US/images/erd.png         | Bin 599343 -> 497220 bytes
 docbook/Developers_Guide/en-US/images/mantis_logo.png | Bin 35725 -> 19036 bytes
 images/mantis_logo.png                                | Bin 35725 -> 19036 bytes
 images/mantis_logo_notext.png                         | Bin 14039 -> 10861 bytes
 images/rel_dependant.png                              | Bin 174 -> 109 bytes
 images/rel_duplicate.png                              | Bin 149 -> 97 bytes
 images/rel_related.png                                | Bin 140 -> 93 bytes

```

### CODE REVIEW

**Comment by dregad** [comment]
Hello,

Thanks for your contribution.

All the png's in css/images are from jquery-ui, so I would suggest you propose your optimization upstream. I don't see much point in patching them locally, only to see the changes reverted the next time we upgrade the library.

**Comment by PeterDaveHello** [comment]
Oh sure, will do!

**Comment by PeterDaveHello** [comment]
Did it here: https://github.com/jquery/jquery-ui/pull/1710, what about this PR? Is it good to merge? At least will help before next upgrade of jquery-ui.

**Comment by vboctor** [comment]
Thanks @PeterDaveHello for your contribution.  We would like to avoid updating our dependencies unless really necessary.  Also in the next release we are including our modern UI where we replaced our own images with fontawesome.  See https://github.com/mantishub/mantisbt/pull/2

So we won't be able to merge this pull request.

**Comment by dregad** [comment]
@vboctor I agree with not patching the jQuery images as per my previous comments, but I was actually thinking about selectively applying the changes to our own bitmaps only. Would you object to that ?

**Comment by PeterDaveHello** [comment]
Upstream merged now, I think we can still patch the non-jquery images?

**Comment by vboctor** [comment]
In the Modern UI we have removed most of the pictures and replaced them with font awesome.  See https://github.com/mantishub/mantisbt/pull/2

Please submit a PR against the modern ui with optimized versions of the remaining images.

**Comment by PeterDaveHello** [comment]
What about just update this PR to make it based on the latest master branch?

**Comment by vboctor** [comment]
@PeterDaveHello The modern UI is now merged into master, please update this PR against latest master.

**Comment by PeterDaveHello** [comment]
@vboctor updated!

**Comment by dregad** [comment]
@PeterDaveHello your PR still includes updates to jQuery-UI standard images. These will be changed whenever they release a new version including the patch you submitted upstream. Until then, kindly make sure you *only* update MantisBT images.

**Comment by PeterDaveHello** [comment]
Should I remove the changes for all the ` css/images/ui-*`? Seems they are not in individual folder, I'll need to confirm that, thanks.

**Comment by syncguru** [comment]
@PeterDaveHello Yes, you should skip images starting with ui-*

**Comment by PeterDaveHello** [comment]
Fixed now, thanks!

**Comment by vboctor** [comment]
👍

**Comment by syncguru** [comment]
👍

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks.

**Comment by dregad** [comment]
Merged in bf7f07ffc9d2eb0523a0931923ff49acc1a087f1

**Pull request closed without merging**
