### PR TITLE
Fix timetracking layout on view issue details

### PR DESCRIPTION
**Pull request by cproensa**
The layout for timetracking box was messed with misplaced tags,
resulting in a distorted layout for the following content in the page.

Fixes: #22291, #22469

### CODE REVIEW

**Comment by atrol** [comment]
Strange, I don't see that #22291 is fixed after this change, and I don't see that #22469 is still an issue in latest master.
Any idea what I am doing wrong? (Restarted web server, cleared browser cache)

**Comment by cproensa** [comment]
Do you have
`$g_time_tracking_enabled = ON;`

**Comment by cproensa** [comment]
@atrol you were right.
there was a misplaced bracket. It was good as long as the time table was expanded, otherwise the layour was still bad.

**Comment by atrol** [comment]
Closed via https://github.com/mantisbt/mantisbt/commit/f6f845217b7df253d1d056ca27d3cd0cf55f3ad4 https://github.com/mantisbt/mantisbt/commit/a49974f45eba85af4ae7cf83378f93fd02ac368d

**Pull request closed without merging**
