### PR TITLE
Support 'png' icons in modern browsers

### PR DESCRIPTION
**Pull request by badfiles**
https://mantisbt.org/bugs/view.php?id=19991

### CODE REVIEW

**Comment by FavioGalvis** [comment]
I don't see any problems with it.
:+1:

**Comment by atrol** [comment]
This will break existing installations that use the default settings as you forgot to change config_defaults_inc.php.

**Comment by FavioGalvis** [comment]
@badfiles just include the modifications of config_inc.php on config_defaults_inc.php
@atrol That will do?

**Comment by badfiles** [comment]
done

**Comment by FavioGalvis** [comment]
:+1:

**Comment by badfiles** [comment]
By the way, there should be a default favicon.png. Can anyone make it?

**Comment by FavioGalvis** [comment]
uuhhhh, hi res. image edition is not on my skills :(

**Comment by atrol** [comment]
Please enter a report for it at www.mantisbt.org/bugs.
This is to track the issue and to have it in change log if the change will make it's way into the product.

Don't think that this is an easy topic because there are just a few lines of code changes.

We have to consider and test all our supported browsers, see https://www.mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.install.requirements.client

I am also not sure if it's a good idea that users will have to provide two formats for the same thing.
Maybe it's better to wait until we support just browsers that can use SVG for it. (SVG as you don't have to deal with different PNG sizes needed to support all platforms in a good way)

**Comment by vboctor** [comment]
What would happen if users just had .png or .ico file for the custom favicon image name that they had setup in their config?

**Comment by l266509** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  Whats status of this PR?

**Comment by dregad** [comment]
> Maybe it's better to wait until we support just browsers that can use SVG for it. 

Not quite there yet it would seem http://caniuse.com/#feat=link-icon-svg... 
For the record, PNG icons support http://caniuse.com/#feat=link-icon-png is good.

Also, an [interesting read]( https://css-tricks.com/favicon-quiz/), and a [tool to generate a set of icons for best cross-browser compatibility]( http://realfavicongenerator.net).

**Comment by vboctor** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
