### PR TITLE
More bug cache

### PR DESCRIPTION
**Pull request by cproensa**
- Following the changes for attachment count cache, it's needed to be called from my-view page.

- Add a cache for custom fields values, since currently they are issuin one query for each value:
This is view-all page with 50 issues and 4 custom fields columns
Before:
DB	Unique queries executed: 274
DB	Total queries executed: 283
DB	Total query execution time: 0.1127 seconds
Page execution time: 0.6414 seconds
After:
DB	Unique queries executed: 75
DB	Total queries executed: 84
DB	Total query execution time: 0.0335 seconds
Page execution time: 0.4558 seconds

Fixes: #21900

- Add cache for bug tags

Fixes: #21900

### CODE REVIEW

**Comment by dregad** [comment]
Out of curiosity, did you also benchmark the increase of memory usage from using the cache ?

**Comment by cproensa** [comment]
@dregad 
i have modified the commits as you suggested.

**Comment by cproensa** [comment]
> Out of curiosity, did you also benchmark the increase of memory usage from using the cache ?

This is a csv export of 34k bugs.
memory usage is probed after each block of 500 bugs is processed

the fields selcted are:
Id,Project,Reporter,Assigned To,Priority,Severity,Reproducibility,Product Version,Tipo,Category,Date Submitted,View Status,Updated,Summary,Status,Resolution,Fixed in Version,attachment(s),#,Tags,customfield1,customfield2

which includes the recently modified native fields plus 2 custom fields

This is with release-1.3.3:

```
CSVEXPORT start
CSVEXPORT running (1) mem: 43298816
CSVEXPORT running (2) mem: 45395968
CSVEXPORT running (3) mem: 45395968
CSVEXPORT running (4) mem: 47493120
CSVEXPORT running (5) mem: 47493120
CSVEXPORT running (6) mem: 51687424
CSVEXPORT running (7) mem: 51687424
CSVEXPORT running (8) mem: 53784576
CSVEXPORT running (9) mem: 55881728
CSVEXPORT running (10) mem: 55881728
CSVEXPORT running (11) mem: 60076032
CSVEXPORT running (12) mem: 62173184
CSVEXPORT running (13) mem: 62173184
CSVEXPORT running (14) mem: 62173184
CSVEXPORT running (15) mem: 64270336
CSVEXPORT running (16) mem: 66367488
CSVEXPORT running (17) mem: 66367488
CSVEXPORT running (18) mem: 70561792
CSVEXPORT running (19) mem: 70561792
CSVEXPORT running (20) mem: 70561792
CSVEXPORT running (21) mem: 74756096
CSVEXPORT running (22) mem: 76906496
CSVEXPORT running (23) mem: 77004800
CSVEXPORT running (24) mem: 79200256
CSVEXPORT running (25) mem: 79298560
CSVEXPORT running (26) mem: 81477632
CSVEXPORT running (27) mem: 83673088
CSVEXPORT running (28) mem: 83771392
CSVEXPORT running (29) mem: 85966848
CSVEXPORT running (30) mem: 88162304
CSVEXPORT running (31) mem: 88260608
CSVEXPORT running (32) mem: 90456064
CSVEXPORT running (33) mem: 92651520
CSVEXPORT running (34) mem: 92749824
CSVEXPORT running (35) mem: 94945280
CSVEXPORT running (36) mem: 97140736
CSVEXPORT running (37) mem: 97239040
CSVEXPORT running (38) mem: 99434496
CSVEXPORT running (39) mem: 101629952
CSVEXPORT running (40) mem: 101728256
CSVEXPORT running (41) mem: 103923712
CSVEXPORT running (42) mem: 104022016
CSVEXPORT running (43) mem: 106217472
CSVEXPORT running (44) mem: 110510080
CSVEXPORT running (45) mem: 110608384
CSVEXPORT running (46) mem: 112803840
CSVEXPORT running (47) mem: 114999296
CSVEXPORT running (48) mem: 115097600
CSVEXPORT running (49) mem: 117293056
CSVEXPORT running (50) mem: 119488512
CSVEXPORT running (51) mem: 119586816
CSVEXPORT running (52) mem: 121782272
CSVEXPORT running (53) mem: 123977728
CSVEXPORT running (54) mem: 124076032
CSVEXPORT running (55) mem: 126271488
CSVEXPORT running (56) mem: 128483328
CSVEXPORT running (57) mem: 128581632
CSVEXPORT running (58) mem: 130777088
CSVEXPORT running (59) mem: 132972544
CSVEXPORT running (60) mem: 133070848
```

the script fails with memory reaching the limit.


Here is is with current branch:

```
CSVEXPORT start
CSVEXPORT running (1) mem: 28356608
CSVEXPORT running (2) mem: 32550912
CSVEXPORT running (3) mem: 32550912
CSVEXPORT running (4) mem: 34648064
CSVEXPORT running (5) mem: 34648064
CSVEXPORT running (6) mem: 34648064
CSVEXPORT running (7) mem: 36745216
CSVEXPORT running (8) mem: 36745216
CSVEXPORT running (9) mem: 36745216
CSVEXPORT running (10) mem: 38842368
CSVEXPORT running (11) mem: 38842368
CSVEXPORT running (12) mem: 38842368
CSVEXPORT running (13) mem: 38842368
CSVEXPORT running (14) mem: 40939520
CSVEXPORT running (15) mem: 40939520
CSVEXPORT running (16) mem: 40939520
CSVEXPORT running (17) mem: 40939520
CSVEXPORT running (18) mem: 45133824
CSVEXPORT running (19) mem: 45133824
CSVEXPORT running (20) mem: 45133824
CSVEXPORT running (21) mem: 45133824
CSVEXPORT running (22) mem: 45182976
CSVEXPORT running (23) mem: 45281280
CSVEXPORT running (24) mem: 45379584
CSVEXPORT running (25) mem: 47575040
CSVEXPORT running (26) mem: 47656960
CSVEXPORT running (27) mem: 47755264
CSVEXPORT running (28) mem: 47853568
CSVEXPORT running (29) mem: 50049024
CSVEXPORT running (30) mem: 50147328
CSVEXPORT running (31) mem: 50245632
CSVEXPORT running (32) mem: 50343936
CSVEXPORT running (33) mem: 52539392
CSVEXPORT running (34) mem: 52637696
CSVEXPORT running (35) mem: 52736000
CSVEXPORT running (36) mem: 52834304
CSVEXPORT running (37) mem: 55029760
CSVEXPORT running (38) mem: 55128064
CSVEXPORT running (39) mem: 55226368
CSVEXPORT running (40) mem: 55324672
CSVEXPORT running (41) mem: 57520128
CSVEXPORT running (42) mem: 57618432
CSVEXPORT running (43) mem: 57716736
CSVEXPORT running (44) mem: 57815040
CSVEXPORT running (45) mem: 60010496
CSVEXPORT running (46) mem: 60108800
CSVEXPORT running (47) mem: 60207104
CSVEXPORT running (48) mem: 60305408
CSVEXPORT running (49) mem: 62500864
CSVEXPORT running (50) mem: 62599168
CSVEXPORT running (51) mem: 62697472
CSVEXPORT running (52) mem: 62795776
CSVEXPORT running (53) mem: 64991232
CSVEXPORT running (54) mem: 65089536
CSVEXPORT running (55) mem: 65187840
CSVEXPORT running (56) mem: 65302528
CSVEXPORT running (57) mem: 67497984
CSVEXPORT running (58) mem: 67596288
CSVEXPORT running (59) mem: 67694592
CSVEXPORT running (60) mem: 67792896
CSVEXPORT running (61) mem: 69988352
CSVEXPORT running (62) mem: 70086656
CSVEXPORT running (63) mem: 70184960
CSVEXPORT running (64) mem: 70283264
CSVEXPORT running (65) mem: 72380416
CSVEXPORT running (66) mem: 72577024
CSVEXPORT running (67) mem: 72675328
CSVEXPORT running (68) mem: 72773632
CSVEXPORT end time: 102.37132692337
CSVEXPORT end mem: 72773632
```

the script now uses less memory, and is able to finish within the memory limits

still, i may investigate the causes of memory increase for each block, even if it's less than previous situation

**Comment by cproensa** [comment]
Also, mention,  the new pushes for tags cache and minor fixes for previous custom fields cache commits
th memory benchmark was made with those in place

**Comment by dregad** [comment]
> investigate the causes of memory increase for each block

If you can, it would be good.

**Comment by cproensa** [comment]
> If you can, it would be good.

i dont think i can at the moment. most of the memory profilers don't work right with php7
I have made some test and i believe, the increasing memory is part of the BugData object: fetch, creation, and existence. Possibly other leakages too in the app or the libraries. Those can be really difficult to find.
The memory used by the independent caches is almost constant and not adding to that increment.

Other fields with potential cache improvement are:
- description/additional information/steps to reproduce
- notes

Loading them by blocks can speed up if those columns were selected, but those are significantly larger objects.
At this point the improvements would happen mainly in the export scripts, because those are not columns that are usually used in web view.

**Comment by cproensa** [comment]
by changing the csv query to be done by blocks (offset, count) the memory decreases significantly
The same run for previous 34k bugs. Time increase in ~20%, but memory is minimal, saving on the buffered query fetch, with smaller result sets.

I will submit those changes in a following PR, as this has been already reviewed.
For the case here, the cache memory is demonstrated under control

```
CSVEXPORT start
CSVEXPORT running (1) mem: 6291456
CSVEXPORT running (2) mem: 10485760
CSVEXPORT running (3) mem: 10485760
CSVEXPORT running (4) mem: 10485760
CSVEXPORT running (5) mem: 10485760
CSVEXPORT running (6) mem: 10485760
CSVEXPORT running (7) mem: 12582912
CSVEXPORT running (8) mem: 12582912
CSVEXPORT running (9) mem: 12582912
CSVEXPORT running (10) mem: 12582912
CSVEXPORT running (11) mem: 12582912
CSVEXPORT running (12) mem: 12582912
CSVEXPORT running (13) mem: 12582912
CSVEXPORT running (14) mem: 12582912
CSVEXPORT running (15) mem: 12582912
CSVEXPORT running (16) mem: 12582912
CSVEXPORT running (17) mem: 12582912
CSVEXPORT running (18) mem: 12582912
CSVEXPORT running (19) mem: 12582912
CSVEXPORT running (20) mem: 12582912
CSVEXPORT running (21) mem: 12582912
CSVEXPORT running (22) mem: 12632064
CSVEXPORT running (23) mem: 12730368
CSVEXPORT running (24) mem: 12828672
CSVEXPORT running (25) mem: 12926976
CSVEXPORT running (26) mem: 13008896
CSVEXPORT running (27) mem: 13107200
CSVEXPORT running (28) mem: 13205504
CSVEXPORT running (29) mem: 13303808
CSVEXPORT running (30) mem: 13402112
CSVEXPORT running (31) mem: 13500416
CSVEXPORT running (32) mem: 13598720
CSVEXPORT running (33) mem: 15794176
CSVEXPORT running (34) mem: 15794176
CSVEXPORT running (35) mem: 15990784
CSVEXPORT running (36) mem: 16089088
CSVEXPORT running (37) mem: 16187392
CSVEXPORT running (38) mem: 16285696
CSVEXPORT running (39) mem: 16384000
CSVEXPORT running (40) mem: 16482304
CSVEXPORT running (41) mem: 16580608
CSVEXPORT running (42) mem: 16678912
CSVEXPORT running (43) mem: 16777216
CSVEXPORT running (44) mem: 16875520
CSVEXPORT running (45) mem: 16973824
CSVEXPORT running (46) mem: 17072128
CSVEXPORT running (47) mem: 17170432
CSVEXPORT running (48) mem: 17268736
CSVEXPORT running (49) mem: 17367040
CSVEXPORT running (50) mem: 17465344
CSVEXPORT running (51) mem: 17563648
CSVEXPORT running (52) mem: 17661952
CSVEXPORT running (53) mem: 17760256
CSVEXPORT running (54) mem: 17858560
CSVEXPORT running (55) mem: 17956864
CSVEXPORT running (56) mem: 18071552
CSVEXPORT running (57) mem: 18169856
CSVEXPORT running (58) mem: 18268160
CSVEXPORT running (59) mem: 18366464
CSVEXPORT running (60) mem: 18464768
CSVEXPORT running (61) mem: 18563072
CSVEXPORT running (62) mem: 18661376
CSVEXPORT running (63) mem: 18759680
CSVEXPORT running (64) mem: 18857984
CSVEXPORT running (65) mem: 18956288
CSVEXPORT running (66) mem: 19054592
CSVEXPORT running (67) mem: 19152896
CSVEXPORT running (68) mem: 19251200
CSVEXPORT end time: 120.65767598152
CSVEXPORT end mem: 19251200


```

**Comment by cproensa** [comment]
@dregad 
i have added new changes after your review.

Now it has reduced the memory use of csv/excel export, as seen in my previous benchmark. The memory increment is due to logs and output buffering. 
As part of testing other excel libs, which outputs to file, the memory usage was, as an example, a constant 12Mb usage.

**Comment by dregad** [comment]
Merged in 31385f2fef8892dfbe9773c1d6f14108cd84d9fe

**Pull request closed without merging**
