### PR TITLE
Re-add strike-through on resolved ticket: Fixes #22492

### PR DESCRIPTION
**Pull request by luzpaz**
MantisBT ticket: http://mantisbt.org/bugs/view.php?id=22492#c57338
Downstream ticket: https://freecadweb.org/tracker/view.php?id=2949

### CODE REVIEW

**Comment by luzpaz** [comment]
Did I add the CSS code to the right place?

**Comment by luzpaz** [comment]
Thanks @syncguru 
@vboctor how do you want me to proceed ? Should I resolve the conflicting code ?

**Comment by vboctor** [comment]
Yes @luzpaz please resolve the conflicting code by rebasing your changes on master.

**Comment by luzpaz** [comment]
rebased and passed travisci. Good to go!

**Comment by vboctor** [comment]
Merged via c368606ecb98c665cf678a038b5af2c2c6d13eed

**Pull request closed without merging**
