### PR TITLE
Upgrade to Ace theme 1.4 & include unminified files

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #21603

### CODE REVIEW

**Comment by dregad** [comment]
Thank you Rafik.

Just a note regarding the file header that you added to the ACE template files. Shouldn't this reference "ACE Template" or whatever it's called, and show copyright information for the original author, instead of making it look like it's an integral part of MantisBT ?

**Comment by syncguru** [comment]
@dregad I switched to using generic gnu GPL license wording as agreed with the theme author at: https://github.com/mantisbt/mantisbt/blob/master/doc/ace-theme-license.txt

**Comment by syncguru** [comment]
@dregad, @vboctor: Added author info, can we get this in?

**Comment by grangeway** [comment]
This looks like you are adding author information to the file as opposed to the original author.

**Comment by vboctor** [comment]
Merged via 6c082930e8e3b98870cfe70b6c8e2e7d88e56501
Thanks @syncguru

**Pull request closed without merging**
