### PR TITLE
Fix lang_load() preformance again.

### PR DESCRIPTION
**Pull request by raspopov**
Fix for: [35198](https://mantisbt.org/bugs/view.php?id=35198).

### CODE REVIEW

**Comment by raspopov** [comment]
I've attached a graphical performance report for different versions (the unit on the charts is 10ns) of `lang_load()` function:

preg_replace() - original code:
lang_load 1 preg_replace

str_starts_with() + substr() - first version:
lang_load 2 str_starts_with

strncmp() + substr() - current version:
lang_load 3 strncmp

index + substr() - proposed in this pull request:
lang_load 4 index

**Comment by dregad** [comment]
Merged in 36481ac9de7333813250933295d2f161329f27dc.

@raspopov Next time you're submitting a PR for an issue that's targeted at the current stable release (2.27.1 here), could you kindly target the corresponding branch (master-2.27) ? It would save me some time when I merge the PR, which I could do straight from GitHub instead of having to fetch locally, rebase and push. Thanks a lot for your cooperation 😄

**Comment by raspopov** [comment]
And I wonder why you're rebasing... 🧐

**Comment by dregad** [comment]
Because I like to keep my Git history as linear as possible

**Pull request closed without merging**
