### PR TITLE
Fix Filter links for resolved/closed custom statuses in Summary By Status report

### PR DESCRIPTION
**Pull request by dregad**
Fixes [#23796](https://mantisbt.org/bugs/view.php?id=23796)

### CODE REVIEW

**Comment by dregad** [comment]
This fix is not complete, as pointed out in https://mantisbt.org/bugs/view.php?id=23796#c58515 I failed to fix processing of the last line (outside of while loop). I think I'll refactor the whole function to get rid of code duplication.

**Comment by atrol** [comment]
> I think I'll refactor the whole function

Keep in mind that there is also a refactoring after your requested it https://github.com/mantisbt/mantisbt/pull/1231#issuecomment-343862062 so you might introduce merge conflicts.

**Comment by dregad** [comment]
Damn I forgot about that one

**Comment by dregad** [comment]
Following merge of #1231, I have rebased the branch and (hopefully) fixed the remaining issue raised in https://mantisbt.org/bugs/view.php?id=23796#c58515

**Pull request merged**
