### PR TITLE
Possibility to write a violation report for CSP

### PR DESCRIPTION
**Pull request by mfoXen**
Try to find reason of BugID [0017491](https://www.mantisbt.org/bugs/view.php?id=17491).
First added some source-comments (sorry for that not being a single commit).
Second splitted the construction of this csp-header to simplyfie future changes (again sorry).
Third added an option to enable/disable an report-uri-directiv to the csp-header.
Finally added <mantishome>\csp\csp_report.php which do log any violations.

To get such a report set $g_report_csp_violation = ON and start using mantis.
As far as an violation appears, the corresponding logfile will be extended - and this way we'll get noticed which csp-directive results in blocking those gravatars.

Note: Also added csp_report_only.php which is for a future csp-read-only -header.

I wasn't sure where to put csp_report*.php and their logs, that's why simply created new subfolder. I'm sure you would relocate that...

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for the PR. 

I noticed the first few commits are part of earlier PR's you sent, which have already been processed (#568, #570). To make code review easier, can you kindly *rebase* your branch on top of master  instead of merging it (then force-push it to github, to update the pull request), and make sure it **only contains commits related** to the changes you're trying to fix. 

Also, since this is a distinct new feature, you should also submit an issue on our tracker, and refer to it in your commit message(s) as appropriate (e.g. `fixes #xxxx` or `issue #xxxx`).

**Comment by mfoXen** [comment]
I'm sorry for that, will rebase it... I'm new to git (not vcs at all) and happy for every hint. :)

**Comment by mfoXen** [comment]
Well, I'll do another PR with some better/splittet commits (incl. messages revering to issues where needed)

**Comment by dregad** [comment]
You know that Git allows you to edit the commits, don't you ? Try `git commit --amend` or `git rebase --interactive`...

**Comment by mfoXen** [comment]
Yes I do allready know, but wanted to splitt my commit. And playing around with reverting and interactive rebasing would be another scenario. :D Just created another PR - hopefully that one is more the way everybody likes. :)

**Pull request closed without merging**
