### PR TITLE
Clickable summaries in view issues page

### PR DESCRIPTION
**Pull request by scfido**
In view all bug page, add a link to the summary column

### CODE REVIEW

**Comment by vboctor** [comment]
Thanks @scfido for your contribution.  This implemented the following [feature request](https://www.mantisbt.org/bugs/view.php?id=8066) in our bug tracker.

Please change the commit message to:

```
Clickable summaries in view issues page

Fixes #8066
```

**Comment by syncguru** [comment]
I wonder if we should make the entire row clickable vs. just summary field. Since the issues table customizable, users may end up with a different configuration that would benefit from similar functionality but on a different field.

**Comment by atrol** [comment]
>  wonder if we should make the entire row clickable vs. just summary field

What will happen with the columns that are providing links to other pages than view.php, e.g. `edit`, `reporter_id` and `handler_id`.

**Comment by syncguru** [comment]
Good question, @atrol 
I don't know for sure. It is better to try it out and evaluate the experience.

**Comment by dregad** [comment]
> I wonder if we should make the entire row clickable vs. just summary field

@syncguru Maybe, but I suggest you take this on as a separate work item.

**Comment by dregad** [comment]
Just stumbled upon this, and realized that I approved it over 3 years ago and never actually merged it... sorry !

**Pull request merged**
