### PR TITLE
Prevent assignment of categories to non-handler users

### PR DESCRIPTION
**Pull request by dregad**
Fixes [#27268](https://mantisbt.org/bugs/view.php?id=27268)

Also includes a minor fix, adding missing error parameter on EMPTY_FIELD error.

### CODE REVIEW

**Comment by atrol** [comment]
@dregad why didn't you prevent assignment on a lower level (`function category_update`) ?

**Comment by dregad** [comment]
> why didn't you prevent assignment on a lower level (`function category_update`) ?

Because at category API level I do not have any context for the update. Without the _project id_, it is not possible to perform the proper access-level check.

**Comment by dregad** [comment]
Actually I take that back, I have it from the category row. 

I'll make the change as suggested, this way it will also be enforced for API calls.

**Review by vboctor — APPROVED** [review]
Make sure that you are handling the default handler for a global category correctly in terms of:

1. Are we checking global access level for the user?
2. Are we checking at assignment time based on the specific issue project? That would be a good check to have anyways, just in case a user's access level got reduced after they were assigned as a handler for a project category.

**Pull request merged**
