### PR TITLE
Support tagging from report issue page

### PR DESCRIPTION
**Pull request by vboctor**
Fixes #9450

### CODE REVIEW

**Comment by atrol** [comment]
Missing update of docbook/Admin_Guide/en-US/config/fields.xml

Looks good at first sight, but I have no time for a deeper look or any tests at the moment.

**Comment by vboctor** [comment]
@atrol I've addressed your comment.  Thanks.

**Comment by vboctor** [comment]
@atrol @dregad any comments on this?

**Comment by dregad** [comment]
+1 on principle, but I didn't have time to test

**Pull request merged**
