### PR TITLE
New feature: New constant LINKS_NOFOLLOW_EXTERNAL to set nofollow lin…

### PR DESCRIPTION
**Pull request by c-schmitz**
…k attributes on external links

Fixes issue https://mantisbt.org/bugs/view.php?id=5271

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
Thanks for your contribution.

I have not had time to actually test this yet, but here's a few remarks following a quick code review.

Please make sure to follow our [coding guidelines](https://mantisbt.org/wiki/doku.php/mantisbt:coding_guidelines). In particular, watch out for
- spaces inside parenthesis, e.g. `function( xxx )`, not `function(xxx)`
- variables naming: Separate words with underscore; prefix: `t_` for local vars, `p_` for parameters
- indent with tabs
- break long lines (no more than 120 chars)

**Comment by c-schmitz** [comment]
Thanks. I cleaned up formatting and variables. Please let me know if you see any more issues.

**Review by dregad — APPROVED** [review]
I reviewed and tested this, for me this PR is (almost) good to go.

Two non-blocking points:
- I'm thinking LINKS_NOFOLLOW_EXTERNAL should be on by default. Thoughts ?
- The new constant should be documented in the Admin Guide

    ```patch
    diff --git a/docbook/Admin_Guide/en-US/config/html.xml b/docbook/Admin_Guide/en-US/config/html.xml
    index 6bdd75096..a05a6c975 100644
    --- a/docbook/Admin_Guide/en-US/config/html.xml
    +++ b/docbook/Admin_Guide/en-US/config/html.xml
    @@ -51,6 +51,13 @@
                                                            Implies <emphasis>LINKS_NOOPENER</emphasis>.
                                                    </para>
                                            </listitem>
    +                                       <listitem>
    +                                               <para><emphasis>LINKS_NOFOLLOW_EXTERNAL</emphasis> -
    +                                                       Links to external sites (i.e. having a different root domain) have the
    +                                                       <ulink url="https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#nofollow">nofollow</ulink>,
    +                                                       instructing search engines not to follow these links.
    +                                               </para>
    +                                       </listitem>
                                    </itemizedlist>
                            </listitem>
                    </varlistentry>
    ```

**Comment by c-schmitz** [comment]
> I'm thinking LINKS_NOFOLLOW_EXTERNAL should be on by default. Thoughts ?

I think the same.

**Comment by dregad** [comment]
Follow-up commits
https://github.com/mantisbt/mantisbt/commits/master/?since=2024-11-21&until=2024-11-21&author=dregad

**Comment by raspopov** [comment]
Look at this please: https://mantisbt.org/bugs/view.php?id=35210

**Pull request merged**
