### PR TITLE
Add a new event EVENT_LDAP_CACHE_ATTRS to extend the LDAP attribute cache

### PR DESCRIPTION
**Pull request by raspopov**
This new event will make it possible to fix any out of date LDAP plugins.

Fixes [35070](https://mantisbt.org/bugs/view.php?id=35070).

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
Please document the new event in the Developer's Guide
(docbook/Developers_Guide/en-US/Events_Reference*.xml)

**Comment by raspopov** [comment]
I added a description and fixed the formatting of the EVENT_CRONJOB event.

**Comment by raspopov** [comment]
Just realised that my PR is almost a copy of #1660 but without UI part.

**Review by dregad — APPROVED** [review]
The changes look OK, but I need to test a bit further and also compare with #1660 to determine if I merge this one or the older PR.

**Comment by dregad** [comment]
Merged in bca481c738fffaf2470fb4b919c3f7dd822becfd

**Pull request closed without merging**
