### PR TITLE
Added hCaptcha

### PR DESCRIPTION
**Pull request by Mythotical**
Added hCaptcha to the system whereas the regular Captcha that only displays on the signup page has been replaced by hCaptcha and it has been added to the lost password page and login password page. All my code additions can be found by searching for "Added by Mythotical" or finding my @todo tags.

In a future update, I'll be releasing changes for reCaptcha addition and if other captcha options exist possibly the addition of those.

**NOTE:** _Even though HCAPTCHA was added, the built-in captcha option still exists and still will work but only on signup._

[MantisBT-hCaptcha-Changes.zip](https://github.com/mantisbt/mantisbt/files/5197545/MantisBT-hCaptcha-Changes.zip)

**config_default_inc.php additions (Variables used in config_inc.php is best option):**
- `$g_signup_use_captcha` (Added HCAPTCHA as option)
- `$g_hcaptcha_site_key` (Self explanatory)
- `$g_hcaptcha_secret_key` (Self explanatory)

**login.php:**
- Added if condition surrounding code only processing code if hCaptcha was completed otherwise presented with an error.

**login_password_page.php:**
- Added if condition to show hCaptcha box only if HCAPTCHA is selected as captcha.

**lost_pwd.php:**
- Added hCaptcha token call and token check.
- Added if condition surrounding code to check for success result before continuing.

**lost_pwd_page.php:**
- Added if condition to show hCaptcha box only if HCAPTCHA is selected as captcha.

**signup.php:**
- Added hCaptcha token call and token check.
- Added if condition surrounding code to check for success result before continuing.

**signup_page.php:**
- Added if condition to show hCaptcha box only if HCAPTCHA is selected as captcha.

**core/html_api.php**
- Added the use of hCaptcha scripts only when HCAPTCHA is selected as captcha.

**core/http_api.php**
- Added src for hcaptcha.com under http_security_headers()

**lang/strings_english.txt:**
Added the following strings under my "Added by Mythotical" tag line.
- `$s_login_captcha_alert = 'Please perform the human check.';`
- `$s_login_captcha_label = 'Human Check';` (under login_password_page.php)
- `$s_lost_password_captcha_alert = 'Please perform the human check.';` (under lost_pwd.php)
- `$s_lost_password_captcha_label = 'Human Check';`
- `$s_signup_captcha_label = 'Human Check';`
- `$MANTIS_ERROR[ERROR_HUMAN_CHECK_INCOMPLETE] = 'You did not complete the human check. Please go back and try again.';`

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
@Mythotical Thanks for your contribution. Several preliminary remarks:

1. You need to **rebase** your feature branch on top of latest master. As it stands, your PR contains a lot of noise that prevents a clean review.
2. Any PR / code submission needs to refer to an issue in our bugtracker https://mantisbt.org/bugs. The issue number must be referenced in the commit(s), e.g. `Fixes #xxxx`

That's for the form. 

Now, there is a deeper problem here, because hCaptcha, however nice it may be, is commercial software (even if free to use) and as such I'm not sure we can put it into MantisBT core which is released under GPL, for legal and/or ethical reasons. For the same reason, we have not and would not switch to Google's reCaptcha.

Now it's true that we *do* have a problem with our current Captcha (SecurImage), because it is EOL and no longer supported, so we need a replacement (see https://mantisbt.org/bugs/view.php?id=27156) and I am not aware of other, viable alternatives in the PHP open-source world source world.

Anyway, I think it would be best to turn this PR into a plugin, adding new Events as needed; then another plugin for reCaptcha or other solutions could easily be added in the future.

**Comment by Mythotical** [comment]
> @Mythotical Thanks for your contribution. Several preliminary remarks:
> 
> 1. You need to **rebase** your feature branch on top of latest master. As it stands, your PR contains a lot of noise that prevents a clean review.
> 2. Any PR / code submission needs to refer to an issue in our bugtracker https://mantisbt.org/bugs. The issue number must be referenced in the commit(s), e.g. `Fixes #xxxx`
> 
> That's for the form.
> 
> Now, there is a deeper problem here, because hCaptcha, however nice it may be, is commercial software (even if free to use) and as such I'm not sure we can put it into MantisBT core which is released under GPL, for legal and/or ethical reasons. For the same reason, we have not and would not switch to Google's reCaptcha.
> 
> Now it's true that we _do_ have a problem with our current Captcha (SecurImage), because it is EOL and no longer supported, so we need a replacement (see https://mantisbt.org/bugs/view.php?id=27156) and I am not aware of other, viable alternatives in the PHP open-source world source world.
> 
> Anyway, I think it would be best to turn this PR into a plugin, adding new Events as needed; then another plugin for reCaptcha or other solutions could easily be added in the future.

1. Yeah thanks, I didn't realize I did that wrong. Not sure what you mean by a lot of noise.
2. I thought this was an open-source system where users can contribute changes without the need to provide a bug fix number.

I understand about hCaptcha, I'll look into replacing the currently built-in captcha system with one that is up-to-date and maintained so that support will be there for it. I'll see what I can find for alternatives to the EOL captcha you use currently. I'll dig and dig until I find something.

Turning it into a plugin would be great but I'm not sure what files I need to edit to add new events and propose those changes so that a proper alternative is out there in a plugin form.

**Comment by dregad** [comment]
>     1. Yeah thanks, I didn't realize I did that wrong.

When you created the PR, you picked the wrong source branch, as shown at the top of this page: `Mythotical wants to merge 121 commits into master-2.24 from master`, which means you're asking us to merge _master_ into _master-2.24_ which does not make sense. You should have picked a the branch in your own fork, where you implemented the changes.

> Not sure what you mean by a lot of noise.

Sorry, I mean there's a whole lot of commits in the PR, which are unrelated to the change you're submitting (i.e. adding hCaptcha). These make the review difficult.

>     2. I thought this was an open-source system where users can contribute changes without the need to provide a bug fix number.

It is open source indeed, but a change is not not just about source code. 

We like to keep our bugtracker and the code in sync, which ensures that changes do appear in the roadmap/changelog, and also if someone looks at GIT in the future, they can lookup the bug ID in the commit and find extra information about the change.

> I understand about hCaptcha, I'll look into replacing the currently built-in captcha system with one that is up-to-date and maintained so that support will be there for it. I'll see what I can find for alternatives to the EOL captcha you use currently. I'll dig and dig until I find something.

That would be great. I did search a bit, without success but maybe you'll have more luck...

> Turning it into a plugin would be great but I'm not sure what files I need to edit to add new events and propose those changes so that a proper alternative is out there in a plugin form.

The most important part about adding new events, is knowing where they need to be triggered and how. The rest is just adding them to `core/events_inc.php` and documenting them.

Once I see what you did for hCaptcha in this PR, I may be able to give you more specific info.

Feel free to ping me on Gitter for a chat if needed.

**Comment by dregad** [comment]
Sorry, I just realized that you provided your changes as a ZIP file. Don't do that...

You need to fork the MantisBT repository, clone it locally, apply your changes, commit, push to your fork, then submit a pull request.
Suggested reading: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by Mythotical** [comment]
> When you created the PR, you picked the wrong source branch, as shown at the top of this page: `Mythotical wants to merge 121 commits into master-2.24 from master`, which means you're asking us to merge _master_ into _master-2.24_ which does not make sense. You should have picked a the branch in your own fork, where you implemented the changes.

Thanks, I'll make sure I do it right from now on. If you want to delete that pull request, go for it.

> Sorry, I mean there's a whole lot of commits in the PR, which are unrelated to the change you're submitting (i.e. adding hCaptcha). These make the review difficult.

Gotcha, I'll do better. Honestly, this is my first time using Github in this fashion, usually, I just download stuff.

> It is open source indeed, but a change is not not just about source code.
> 
> We like to keep our bugtracker and the code in sync, which ensures that changes do appear in the roadmap/changelog, and also if someone looks at GIT in the future, they can lookup the bug ID in the commit and find extra information about the change.

So, if I want to provide changes, should I start a bug report then link to it?

> That would be great. I did search a bit, without success but maybe you'll have more luck...

I've actually had some luck, found a couple of good ones but I'm looking for that one that just screams "WOW" before I decide.
 
> The most important part about adding new events, is knowing where they need to be triggered and how. The rest is just adding them to `core/events_inc.php` and documenting them.

I know where a couple of events are needed, I'll add them and see what happens.

> Once I see what you did for hCaptcha in this PR, I may be able to give you more specific info.

The best way is to download the zip and look for my @todo marks.

**Comment by dregad** [comment]
As this PR is not usable in its current form, I'm going to close it. Please submit again.

**Pull request closed without merging**
