### PR TITLE
MantisBT Modern UI

### PR DESCRIPTION
**Pull request by syncguru**
Over the past few months I've been working on building a modern UI for MantisBT. The main drivers for this effort are:  (1) a request from MantisBT core team back in January when I delivered the [mantisbt.org](http://mantisbt.org/) modern website that you see live today,  (2) a loud and clear feedback from MantisBT/[MantisHub](http://www.mantishub.com/) users who publicly and privately spoke against the current UI , (3) a personal desire to contribute to MantisBT open source effort with a lasting positive impact on both end users satisfaction and product adoption.

The changes in this pull request are:
* Integrate with [Bootstrap v3.2](http://getbootstrap.com/) framework as the foundation for all Mantis UI elements.
* Use [Fontawesome](http://fortawesome.github.io/Font-Awesome/) for vector based icons.
* Redesign Layout & Navigation
* Update all pages with the new style, look and feel
* Improved experience on mobile devices

The changes here are just the foundation of the MantisBT Modern UI with functional parity to the existing one across all features (including deprecated ones like news).  Bootstrap also provides good foundation for building a mobile friendly UI.  The existing work just scratches the surface in the mobile space, but we can do much more there.  We can also revisit some of the existing workflows to improve the usability and go beyond the modern looking UI.

Please note that this PR disables firefox security headers to address the avatar issue reported here:
[0017491](http://www.mantisbt.org/bugs/view.php?id=17491): Avatars are not showing on Firefox

Here are also some screenshots:

screenshot 2014-08-14 23 24 42

screenshot 2014-08-14 23 26 23

screenshot 2014-08-14 23 27 33

screenshot 2014-08-14 23 28 15

screenshot 2014-08-14 23 28 34

Screenshots of the new UI on iOS 5:

screenshot 2014-08-30 19 52 11

### CODE REVIEW

**Comment by luzpaz** [comment]
This is incredible. Keep going! :+1:

**Comment by kroimon** [comment]
Yes please! Would be great to see this in Mantis!

**Comment by Bubka3** [comment]
Glad to see this is happening.

First impressions are everything for an end-user and the default just doesn't cut it in 2015.

**Comment by dregad** [comment]
Thanks for the update !

**Comment by luzpaz** [comment]
:+1:

**Comment by FavioGalvis** [comment]
Hey @syncguru, great work.
:+1: 
I have been using and bugfixing your fork and works great.

Can we please get this updated to master? we dont want to get behind to much :)

Thanks!

**Comment by badfiles** [comment]
:+1:
Keep it up, please

**Comment by ToanDangIT** [comment]
Love it. Please keep this going.

**Comment by cobexer** [comment]
The burger button on the mobile version should be on the same side as the menu - I had to press it a few times to notice that it changes something on the other end of the screen - and then the menu could probably work more like it does in apps (like in the GMail app for Android)

Then there is the horizontal scrolling - very bad on mobile where there is no scroll indication... not sure how to fix that tough.

Actually the ui still seems to use lots of tables that require lots of horizontal scrolling making them responsive may be a tough challenge...

**Comment by cobexer** [comment]
I also should point out that on the view Issue Details page there are 3 headers, with lots of "wasted" screen space:
 * the top bar with the static "Mantis Bug Tracker" text (duplicated from the window title) the Menu button and two menus - the menus could very well be placed in the menu on the left
 * the bar with a duplication of my user name, a hardly useful re-implementation of my browser history and the very important search box (which after the changes suggested above has enough room there).
 * and the "View Issue Details" header that grabs a lot of visual attention - but provides 0 information - and has a non working burger button (the icon should either be changed or do something useful.)

I believe the View Issue Details heading should be replaced by the Summary field.

I hope you consider such suggestions as useful feedback :) because I definitely like where this is going.

**Comment by ptsimard** [comment]
Hello @syncguru ! I've installed your modern-ui-2 branch (I like it!) and wanted to report this issue:

mantisbt-modern-ui-2-custom-fields

**Comment by ptsimard** [comment]
Here is some more feedback. I hope it can help. See screenshot.

mantisbt design improvement

**Comment by dregad** [comment]
@ptsimard many thanks for your valuable feedback. I would suggest you [open issues on our tracker](https://www.mantisbt.org/bugs/bug_report_page.php) for each of your findings / recommendations instead of reporting everything here, it would facilitate tracking and follow-up. 

Make sure you pick Category = *ui* Product Version = *2.0.x*

**Pull request merged**
