### PR TITLE
Return consistent status codes from REST API delete operations

### PR DESCRIPTION
**Pull request by dregad**
Fixes [#32858](https://mantisbt.org/bugs/view.php?id=32858) + code cleanup

Follows up on discussion in #1905

### CODE REVIEW

**Comment by dregad** [comment]
Note: there are currently no test cases for REST API /projects endpoint

**Review by vboctor — CHANGES_REQUESTED** [review]
Thanks @dregad

The API tests shouldn't call internal APIs like tag_exists(). The need to do so is a symptom of missing APIs and couples the API tests with the codebase. Please remove such calls and identify gaps that we need with todos or issues in bug tracker - e.g. if we are missing a Get Tags API or equivalent.

**Comment by dregad** [comment]
> The API tests shouldn't call internal APIs like tag_exists(). The need to do so is a symptom of missing APIs and couples the API tests with the codebase.

I can hear the argument about such usage being an indicator that the API has missing endpoints and needs improvement. On the other hand, I strongly disagree that the internal calls should be removed before the new endpoints are available. 

Doing so means reducing the tests's coverage and quality, which does not make sense. I'm OK to flag them with a TODO, but getting rid of them is not a good idea.

Some of these usages, e.g. the loop to find a non-existing Id or ensuring a tag name's uniqueness, make absolutely no sense to implement with repeated REST calls; it adds no value, and is less efficient.

**Comment by dregad** [comment]
Opened [#32863](https://mantisbt.org/bugs/view.php?id=32863) to track adding CRUD endpoints for Tags management.

**Review by vboctor — APPROVED** [review]

**Pull request merged**
