### PR TITLE
Highlight due date when the date has passed

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #21642

screen shot 2016-08-25 at 7 52 11 pm

### CODE REVIEW

**Comment by vboctor** [comment]
Did you check the case where the due date is visible on the View Issues page as a column?  I would compare the behavior with the classic UI to make sure we covered all the cases.

**Comment by syncguru** [comment]
@vboctor Yes, I looked at that case. It is the same as in the issue details page. The table cell is in view issues page decorated with 'overdue' css class when overdue which will be highlighted as shown in the image above.

**Comment by vboctor** [comment]
👍

**Comment by dregad** [comment]
@syncguru in terms of UI, I was wondering since you removed colored backgrounds pretty much everywhere (replacing them with colored squares), why you didn't follow the same approach here.

**Pull request merged**
