### PR TITLE
Added user avatar to view_user_page, see issue #0016248

### PR DESCRIPTION
**Pull request by andersruneson**
In case you still accept patches for the 1.2.x-series, here is one that adds avatar (if configured) to the view_user_page.

screenshot from 2015-02-02 20 18 03

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution.

In terms of design, IMO having the avatar to the left of the labels breaks the consistency of the UI, I think it would be better to have it on the right-hand side. Also, the title row ("User Information") no longer spans correctly.

That being said, since this is a new feature and not a bug fix, it should go in master and not in 1.2. Would you mind porting your branch  ?

**Comment by andersruneson** [comment]
My motivation for this PR is to maintain fewer patches in my own installation for every update to Mantis stable. Would you consider merging in 1.2 if I fix your comments?

As for master/1.3 I can port this as soon as I have an installation for testing.

**Comment by dregad** [comment]
> Would you consider merging in 1.2 if I fix your comments?

The change is quite harmless and limited in scope, so yes I would consider it.

**Comment by andersruneson** [comment]
Updated branch.
screenshot from 2015-02-04 09 19 25

**Comment by l266509** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  Whats status of this PR?

**Pull request closed without merging**
