### PR TITLE
Fixes #21805 'uncaught error ... requires jQuery' on signup and login page

### PR DESCRIPTION
**Pull request by LeoZandvliet**
Fixes #21805
This will fix 'uncaught error ... requires jQuery' on login and signup page.
Added html_head_javascript() to layout_login_page_begin()

### CODE REVIEW

**Comment by LeoZandvliet** [comment]
Its fixing #21805 from mantis' own bugtracker, sorry I didnt know. Didnt see any 'issues' topic here on Github... 
Also changed the line of code which was wrongly copied I suppose, now it must be correct.

**Comment by dregad** [comment]
@syncguru please confirm if that's OK for you as well.

**Comment by syncguru** [comment]
@dregad Looks good to me.

**Comment by LeoZandvliet** [comment]
Ok I think it's official now but I don't know how to merge my two changes. I can't through the webinterface nor through GitHub Desktop. Well I think it's possible through Desktop but nothing changes on this page if I'm updating/syncing in that application. Also getting the message I'm not allowed to push local changes to this PR922.
I'm very sorry if I don't understand this, just trying to help :(

**Comment by vboctor** [comment]
Merged via 60f4e5fb129dbc34116fa7ce3556058fabc0d9fe - thanks @LeoZandvliet

**Comment by dregad** [comment]
> I don't know how to merge my two changes. I can't through the webinterface nor through GitHub Desktop.
> not allowed to push local changes to this PR922

@LeoZandvliet AFAIK, this is not feasible from Github's web interface. I don't use Github desktop so I'm not sure what the tool can do. 

In any case, this is best performed via command-line. I suggest you read this excellent blog article to learn more about it: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Pull request closed without merging**
