### PR TITLE
[CLEANUP] Remove trailing whitespaces and tabs from core files

### PR DESCRIPTION
**Pull request by keessonnema**
While we're adding our own features into Mantisbt we come across some flaws. One of them is the lack of code-standards (https://www.mantisbt.org/wiki/doku.php/mantisbt:coding_guidelines) and the other one is trailing whitespaces and/or tabs.

This removes all trailing whitespaces and tabs from core files

### CODE REVIEW

**Comment by dregad** [comment]
Can you please elaborate on what you mean by _the lack of code-standards_ ? As you have yourself pointed out, we have them defined in our wiki...

**Comment by keessonnema** [comment]
> Can you please elaborate on what you mean by _the lack of code-standards_ ? As you have yourself pointed out, we have them defined in our wiki...

I'm glad to help fix this, but I see spaces, tabs and spaces & tabs in the same function throughout the source. The wiki states tabs with a length of 4 spaces, which is totally fine, it's just that some files aren't following the standards.

Not to be rude, just pointing those things out.

**Comment by dregad** [comment]
OK I understand now. I thought you were saying we did not have standards, which was kind of confusing.

> some files aren't following the standards.

Yeah I know... A few years ago I started working on defining PHP CodeSniffer rules to automate checking that, but never finished it. Too many things to do and too little time.

Nowadays I tend to fix these whenever I see them, but the problem is that without systematic and automated compliance checks against the standards, such deviations tend to creep back in.

**Comment by keessonnema** [comment]
> Based on the above, I wouldn't merge.
To be honest I expected this. I'm glad you guys are aware and have a workflow to 'fix' them. I'd be a little more strict in terms of pull-requests. Just to make sure everything is perfect (correct tabs, code-standards) from now on (not when it's a breaking change that is needed ofcourse).

The fact that we're actively using Mantisbt in our company and I'm the one responsible for updates / fixes (this due to our own custom changes) makes me feel involved in getting the code to be as good as possible.

**Comment by vboctor** [comment]
> The fact that we're actively using Mantisbt in our company and I'm the one responsible for updates / fixes (this due to our own custom changes) makes me feel involved in getting the code to be as good as possible.

That's great @keessonnema.  We welcome your contributions for functional improvements, whether they are features, bug fixes, or generalizations of stuff you found useful in your organization.  To get early feedback for improvements that are not small, engage with us in the bug tracker.

**Comment by dregad** [comment]
Closing the PR based on @vboctor's feedback.

**Pull request closed without merging**
