### PR TITLE
Add support for pasting images to forms with dropzone

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #21797

### CODE REVIEW

**Comment by syncguru** [comment]
You are right - fixed.

**Comment by atrol** [comment]
The following behavior is convenient, but a bit strange.
Nut sure if it's intended.

- Copy an image to clipboard
- Click `Report Issue`
- Enter Ctrl+V in `Summary` field

As a result, the image is added as attachment.

**Comment by atrol** [comment]
Does not work in Safari.

**Comment by vboctor** [comment]
I have done few test cases:

1. Copy one file and paste.
2. Copy multiple files and paste
3. Copy an image (e.g. screenshot) then paste.

I have had issues with copying and pasting multiple issues.

- In Firefox - all file names are pasted in text box, but none added to dropzone.
- In Chrome - all file names are added, but only one image added to dropzone.

**Comment by syncguru** [comment]
@atrol: Thanks for giving this a try.

1- The behavior is intended for paste functionality. I capture any paste event over the surface area of the form. Other implementations I've seen covering the entire document. Reducing the surface area will make pasting less useful.
2- It works for me on Safari.  I am not sure about IE since I cannot test. Notice that if we have issues with a browser or version the paste functionality won't work but you still can do what you do today.

**Comment by syncguru** [comment]
@atrol: Thanks for giving this a try.
The copy/paste functionality appears to be intended for taking a snapshot or copying image from a html page. Copying multiple files from a file manager use case seems to be nonuniformly supported as a drag and drop. Browsers behave differently if you try to copy & paste and that is what you are experiencing:
See [this](https://stackoverflow.com/questions/18055422/how-to-receive-php-image-data-over-copy-n-paste-javascript-with-xmlhttprequest) StackOverflow thread from more details.

**Comment by cproensa** [comment]
For me it works fine.
I can point:
- By doing repeated ctl-v, the same file is duplicated N times. It would be good if this could be detected to avoid duplication
- I miss some visual tool, button, etc that allows to paste from the ui. At least to make the user aware that this possibility exists.

**Comment by syncguru** [comment]
> I miss some visual tool, button, etc that allows to paste from the ui. At least to make the user aware that this possibility exists.

@cproensa do you have example of what that would look like

**Comment by cproensa** [comment]
>> I miss some visual tool, button, etc that allows to paste from the ui. At least to make the user aware that this possibility exists.

> @cproensa do you have example of what that would look like

Probably just modifying the dropzone text is enough: "drop files here to upload", adding a hint that pasting images is possible

**Comment by vboctor** [comment]
@syncguru I would like to merge this.  Are you planning any tweaks?

**Comment by syncguru** [comment]
@vboctor Yes, I will make a text change as suggested by @cproensa ... give me a few mins to update the PR.

**Comment by syncguru** [comment]
@vboctor done.

I used the same expression as in github
Screen Shot 2019-08-03 at 3 42 03 PM

**Pull request merged**
