### PR TITLE
Don't cache users in project_get_all_user_rows()

### PR DESCRIPTION
**Pull request by cproensa**
Adjustments to user rows cache in project_get_all_user_rows()
Bypassing cache when it's not actually needed, helps with the performance issues in #17577
With this fix I'm experiencing about 30~40% improvement in response time.

### CODE REVIEW

**Comment by dregad** [comment]
@cproensa does this actually *fix* [#17577](https://www.mantisbt.org/bugs/view.php?id=17577), or is it just an improvement ?

**Comment by cproensa** [comment]
Its not a full fix. This addresses one of the problems behind that issue. 
Being this a very simple change, I submitted separatedly from a more complex refactor.

**Comment by dregad** [comment]
After testing, I confirm a rather drastic improvement. 

Loading the Configuration Report Page with a dump of mantisbt.org database (over 31K user accounts), my dev box shows the following results (average over 3 executions):

Code base | Page loading time | Memory usage
---|---:|---:
[Current master](f18505cf0151db8a7385b55b295c9fb6d3da3907) | 4.3425 s | 142'020 KiB
This PR | 2.5059 s | 49'536 KiB
**Improvement** | **-42.3%** | **-65.1%**

So, +1 from me. Thanks Carlos, good job !

**Comment by dregad** [comment]
Merged in cd8fa25fa69f50fd2ccba5b9f521411bbefaa063.

**Comment by dregad** [comment]
For the record, this partially covers #668

**Pull request closed without merging**
