### PR TITLE
Update account verify page for modern ui

### PR DESCRIPTION
**Pull request by cproensa**
Fixes: #21684

### CODE REVIEW

**Comment by cproensa** [comment]
@syncguru 
I'd want this page to show only the main form, without sidebar, navigation, etc
If i use layout_login_page_begin(), the main form is not displayed
I can't find a way to do that properly, please have a look.

**Comment by dregad** [comment]
I'm not the resident modern UI expert here, but as reference _login_page.php_ has the kind of layout you are looking for, so maybe you can adapt it to your purposes.

**Comment by syncguru** [comment]
@cproensa - The login pages uses a different layout helpers function as @dregad pointed out. You would want to use layout_login_page_begin() & end() instead. Examples to look at are login_page.php, signup.php, lost_pwd_page.php ...

**Comment by cproensa** [comment]
If i use layout_login_page_begin() it's not working 100%...
note that those pages you said are not using the "blue widget stuff" css, (the styles are different)

if i use: layout_page_header() + layout_login_page_begin()
there is a margin at left
seleccion_051


if i use only layout_login_page_begin(), the form-div is not rendered:
seleccion_050

**Comment by jllano** [comment]
Hi,

I'm adding a reference with my PR on the issue as well. 
https://github.com/mantisbt/mantisbt/pull/895

**Comment by vboctor** [comment]
Closing this in favor of #895

**Pull request closed without merging**
