### PR TITLE
Additional buttons proposal

### PR DESCRIPTION
**Pull request by paspiz85**
I want add extra buttons in header. Those buttons are added via global configuration and can require an access level.
Default is a button to display link to Mantis GitHub project for developer access level but I can change it to an empty array (no buttons at all).
Please tell me if it is usefull or can be do it better.
Thank you

### CODE REVIEW

**Comment by paspiz85** [comment]
I will develop a plugin to do this change. Thanks for your time

**Comment by dregad** [comment]
You're welcome, and thanks for your understanding. Let me know if you need some help with the plugin. Remember that the event trigger does not exist yet, it will need to be added; you're welcome to submit a pull request for that.

**Comment by dregad** [comment]
> How I can register at bugtracker at https://mantisbt.org/bugs/ ? With anonymous login I cannot add issues

Sorry about that, have been under we severe spam attacks, and had to disable registration as things were becoming impossible to manage. 

I have created an account for you, you should receive a notification to reset password by e-mail.

I will take a look at your code as time allows.

**Comment by dregad** [comment]
If you have questions, feel free to get in touch via our [Matrix](https://matrix.to/#/#mantisbt_mantisbt:gitter.im).

**Pull request closed without merging**
