### PR TITLE
Use CDN-related functions in MantisGraph

### PR DESCRIPTION
**Pull request by badfiles**
- add missing base64 alignment
- add comment on howto calculate hashes

### CODE REVIEW

**Comment by vboctor** [comment]
@badfiles thanks, this was on my todo list, but I was waiting for potentially using npm/composer to pull the dependencies for local package.

btw, if the hashes were incorrect due to the missing '=' why wasn't the code failing?  Was it creating warnings in the browser console?

**Comment by badfiles** [comment]
The hashes are correct even without '=', browsers are smart enough to assume there must be alignment.
With '=' is what they should be.

**Comment by vboctor** [comment]
:+1:

**Comment by syncguru** [comment]
👍

**Comment by atrol** [comment]
:+1:

**Comment by vboctor** [comment]
Merged via c3ad66cc459642053b7b4aa59027cfa039a1e886

**Pull request closed without merging**
