### PR TITLE
Attachment to new tab

### PR DESCRIPTION
**Pull request by lucmuller**
This pull request implements the code review suggested changes in #1767
I would be glad to see them merged as having the attachement opened in a new tab would be helpful !

Fixes [#27551](https://mantisbt.org/bugs/view.php?id=27551)

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution. I'll review when I have some time, and get back to you.

**Comment by vboctor** [comment]
Thanks, @lucmuller, for your PR.

This functionality comes up every few years with different implementations. At one point, we had links open in the current tab with an icon next to them to have the user choose to open in a new tab. We then removed it since it was considered redundant to the browser's native support for opening in the current window vs. the new tab vs. the new window. I'm not sure why we would add this again.

**Comment by dregad** [comment]
@vboctor just making sure you're aware, that this is not about URL links (what you seem to be referring to), but links to attachments.

For context, please read https://mantisbt.org/forums/viewtopic.php?f=2&t=25561

**Comment by lucmuller** [comment]
The point of my PR is only to respond to code reviews in #1767.

About links, there's already a configuration to handle them :
$g_html_make_links =  LINKS_NEW_WINDOW | LINKS_NOOPENER;

This PR would allow a new configuration to handle filedownload in the same way :
$g_attachment_to_new_tab = TRUE;

**Comment by dregad** [comment]
Merged in d1cc59114e6ff3498d1f874557b8a667e19b86c7

Thanks @lucmuller @MaloMn for your contribution !

**Pull request closed without merging**
