### PR TITLE
Master 1.3.x

### PR DESCRIPTION
**Pull request by Yanual**
To fixe #23558
Factorization of the following PRs:
https://github.com/mantisbt/mantisbt/pull/1180
https://github.com/mantisbt/mantisbt/pull/1178
https://github.com/mantisbt/mantisbt/pull/986

### CODE REVIEW

**Comment by dregad** [comment]
@Yanual thanks for the pull request. [As mentioned by @atrol](https://www.mantisbt.org/bugs/view.php?id=23558#c58104), the 1.3 branch is in maintenance mode. IMO his last line is not correct, we only apply security and bug fixes to it, no enhancements or new features. 

On a strictly formal note for future patches, please make sure that your commit messages adhere to our [guidelines](http://www.mantisbt.org/wiki/doku.php/mantisbt:git_commit_messages) - *Update xxxx* is useless as it does not give any indication of what the change is about or why it is needed.

**Comment by Yanual** [comment]
@dregad
Atrol mentioned: "... Of course, there would still be improvements if a community member sent a pull request to https://github.com/mantisbt/mantisbt ..."

I'm a French, maybe that's why I do not have the finesse of the English language, for you what is the definition of "improvements", for me it's not only "bug fixes and security "

I propose an improvement in performance and not functional progress.

**Comment by atrol** [comment]
> I'm a French, maybe that's why I do not have the finesse of the English language,

I'm a German, so don't expect a perfect English.

> Atrol mentioned: "... Of course, there would still be improvements if a community member sent a pull request to https://github.com/mantisbt/mantisbt ..."

Seems I should have written: `there could still be improvements ...`

1.3.x is quite stable and any change in 1.3.x could introduce regressions and new bugs.
Changing base technology is always a risk and needs some time to review and test.

Keep in mind that 1.3.x supports older PHP versions, databases and browsers than 2.x.
You can't just reapply the changes from 2.x, but have also to ensure that it works in any 1.3.x supported environment.

Keep also in mind that we did not get similar issues from our user community and that I was not able to reproduce your issue, https://www.mantisbt.org/bugs/view.php?id=23558#c58096

Implementing your changes will not help that much users, e.g. check the download statistics:
https://sourceforge.net/projects/mantisbt/files/mantis-stable/
Quite a lot 2.8.0 downloads, but hardly any 1.3.12, so I am not sure if your changes are worth to risk stability.

There are not that many MantisBT core developers and AFAIK none of them is running 1.3.x in production.
Please understand that we have to focus, and the focus is on latest stable branch, but not the old 1.3.x.

But let's wait also for feedback from @vboctor

**Comment by dregad** [comment]
> I'm a French, maybe that's why I do not have the finesse of the English language

And I'm Swiss... On a tous nos petits problèmes :wink:

**Comment by Yanual** [comment]
I understand your goal of stability.

I was just proposing to make a contribution with modifications already made by other experienced developers in the community. It does not seem to me that this code is subject to an incompatibility with the different version of php.

I gained more than a second with these changes. PHP7 saved me almost half a second.

I can continue to maintain these advances. I just wanted to share its with other users.
It's OK for me, and thank you for your time.

**Comment by dregad** [comment]
Thanks for your understanding.

**Pull request closed without merging**
