### PR TITLE
	Add Bug title for bug "view.php"

### PR DESCRIPTION
**Pull request by comxd**
image

### CODE REVIEW

**Comment by atrol** [comment]
I am wondering if we should display the summary where we have "View Issue Details" at the moment.
So we would not waste any vertical space.

BTW, we should also replace the icon left beside "View Issue Details" as it looks like a burger menu and you might expect some menu entries when clicking on it.

**Comment by comxd** [comment]
Hi all,

Ok I fully agree with you and I have edited my proposal.

image

**Comment by comxd** [comment]
<p class="lead"></p>:
image

Summary into the table header with <b> only for the summary (not ticket ID):
image

I prefer the second proposal with the summary into the header with <b>.

**Comment by vboctor** [comment]
@comxd I'm OK with the latest proposal.  Not sure if we need to just have the title as bold, maybe we should have issue id + summary as bold.

@syncguru @dregad @atrol any objections on going forward with latest proposal?

**Comment by atrol** [comment]
I checkout out latest code of comxd's master branch, which is what you see at https://github.com/mantisbt/mantisbt/pull/1023#issuecomment-278695588

I am not sure if bold is needed.
Don't look at the resized GitHub preview, at least click on it to get the original resolution, or even better try the code in your test installation. My rendering using latest Firefox on Windows is even a bit better readable  than the screenshot with the original resolution.

**Comment by comxd** [comment]
Hi all,

The title is very important, and title with no bold is not sufficiently visible in my opinion.

We can reduce the amont of bold? like 300/400?

**Comment by syncguru** [comment]
-1 

- I am on-board with the need to have a issue title be prominent at the top of the details page.
- With that said, I don't like the designs presented thus far. I am strongly object to using the table header for title. Not to mention how bad the experience is on small screens.

I'd like to see us come closer to how Jira represent issue title as shown in this example: https://jira.atlassian.com/browse/TRANS-2343?jql=

**Comment by syncguru** [comment]
I took a stab at it. Feedback welcome:

screen shot 2017-03-17 at 1 12 51 pm

screen shot 2017-03-17 at 1 22 18 pm

**Comment by syncguru** [comment]
@comxd what do you think of the design above?

**Comment by syncguru** [comment]
Created issue to track this: https://www.mantisbt.org/bugs/view.php?id=22539

**Comment by dregad** [comment]
While I like the addition of the color square reflecting the issue's status, @comxd's proposal had 2 things which were IMHO better to make the title stand out: 
1. stronger contrast for the title bar's background color
2. bold text for issue summary

**Comment by syncguru** [comment]
@dregad 

1- Try to click on the image to see it at full scale. The title should appear much more prominent than having it inside a think dark blue strip.

2- The title is bolded in small screen version (the one shown was not bolded).

**Comment by dregad** [comment]
> Try to click on the image to see it at full scale

I did. And I don't like the proposal's light gray background is very close to that of the fields names, and it makes the bug data section looks different than the other sections on the page.

The bold text is a detail, I can live with or without it.

**Comment by syncguru** [comment]
The usage of blue header has always been for static titles. Adding a dynamic title that could potentially be multi-line breaks the consistency. Beside it is quite unusable on small screen.

**Comment by comxd** [comment]
Hi all,
I like the last version of @syncguru but with the title in bold like my previous proposal?

**Comment by dregad** [comment]
@syncguru 

> The usage of blue header has always been for static titles

It has always been for *titles* (period). Whether the title itself is static or dynamic is irrelevant IMO.

> Adding a dynamic title that could potentially be multi-line breaks the consistency. 

I see more of a consistency break by NOT having a blue title on top of that section.

> Beside it is quite unusable on small screen.

I don't see in what way it would be less usable than your proposal. If there's a long title, then we'll have a taller section on a narrow screen. That is independent from the colors.

If what you mean is that we shouldn't be using the standard "title" CSS used for other sections, I'm fine with that. I see no problem with using a specialized class for this purpose. But I maintain that we should use the same colors and layout as other sections titles.

**Comment by vboctor** [comment]
@syncguru I will close this PR due to inactivity, feel free to re-open or create a new PR if you revisit this work.

**Comment by comxd** [comment]
Hi all, currently we use a Tampermonkey script, we share rendering result with you:

image

image

**Pull request closed without merging**
