### PR TITLE
some small html adjustments to make it easier to apply custom styles

### PR DESCRIPTION
**Pull request by schriftgestalt**
Fixes: #0019587: To many styles are hard coded in HTML

### CODE REVIEW

**Comment by vboctor** [comment]
Thanks @schriftgestalt for your contribution.

We have a new modern UI (#272) that is ready for checkin after branch for 1.3.  I would rather wait for this to happen rather than change styles and cause merge pain.

**Comment by dregad** [comment]
Considering how limited these changes are, I don't think they would cause that much pain to merge...  but as the modern UI branch is completely stale I can't say for sure. Maybe @syncguru could update it to refresh the PR ?

**Comment by vboctor** [comment]
@syncguru has kept the Modern UI up-to-date, tested and is ready to merge to master once we create the 1.3 branch.

If we want to merge this, then ideally we do that once the 1.3 branch is created.  Which I hope we do create soon and get 1.3.0rc1 out.

**Comment by syncguru** [comment]
I’ve not updated the PR in a while to avoid distracting the team from 1.3 work. But I can refresh it anytime you guys like.

There were quite a bit of fixes and tweaks to it over the last few months. It is now more ready to merge than ever before.


Thanks,
Rafik

**Comment by dregad** [comment]
It's actually a sad truth that I have enough distractions as it is ;-)

Anyway, refreshing #272 would help evaluating the amount churn a given change (such as this PR) would actually produce, so if you don't mind, please go ahead.

I've actually sampled the UI on MantisHub a few weeks back and indeed it's much more polished than when I tested the earlier versions. Now I can only wish I had more free time to tie up the loose ends and get 1.3 out the door :-(

**Comment by syncguru** [comment]
@dregad #272 should be up to date now. As of my latest check-in on the April the 14th.

**Comment by l266509** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  Whats status of this PR?

**Comment by vboctor** [comment]
Closing this PR since it is outdated.  @schriftgestalt feel free to create a new PR, if still needed, based on latest from `master` branch.

**Pull request closed without merging**
