### PR TITLE
Fixed Notes added on status change being set to private

### PR DESCRIPTION
**Pull request by jllano**
This fix is when adding notes on status change, notes are set to private always even though the private box is unticked.

Fixes #21701
private_issue

### CODE REVIEW

**Comment by dregad** [comment]
> situation wherein user is not able to view or set the note's view state

Check `$g_set_view_status_threshold` and `$g_set_view_status_threshold`

**Comment by dregad** [comment]
@jllano I fail to see how your latest commit addresses my review comment, as `$g_default_bugnote_view_status` is still not taken into consideration.

**Comment by jllano** [comment]
I got your point @dregad, let me check it.

**Comment by jllano** [comment]
@dregad , Could you clarify what's the main purpose of $g_default_bugnote_view_status? isn't  that for adding a default checked if $g_default_bugnote_view_status is private when adding a Notes on status change only? any other purpose?

**Comment by dregad** [comment]
As documented https://mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.config.defaults

**Comment by dregad** [comment]
@jllano what's the status on this ?

**Comment by jllano** [comment]
My apologies @dregad, but been swamped with other tickets few days ago. I'll have to get this back later. In the meantime you may handle this if you want. 👍

**Comment by vboctor** [comment]
Closing this and re-open a new pull request once a fix is available.

**Pull request closed without merging**
