### PR TITLE
PHPMailer fixes

### PR DESCRIPTION
**Pull request by dregad**
- Use new namespaced PHPMailer exception 
- Adjust case of PHPMailer method names 
- Use PHPMailer::getSMTPInstance() 
- PHPDoc / code cleanup

Fixes [#25566](https://mantisbt.org/bugs/view.php?id=25566)

### CODE REVIEW

**Comment by dregad** [comment]
Note: failed build _continuous-integration/travis-ci/push_ can be ignored, it is the consequence of my pushing the branch to mantisbt/mantisbt instead of my own fork, and then deleting the branch.

**Comment by vboctor** [comment]
@dregad should this go into `master-2.19`?

**Comment by dregad** [comment]
> should this go into master-2.19?

Yes, I'll backport it.

Note that this does not cover whatever issue you experienced with TLS, as don't have a setup to test/reproduce this.

**Comment by dregad** [comment]
Rebased branch to master-2.19.

@vboctor Shall I merge as-is, or are you planning to provide further info on the TLS issue ?

**Comment by vboctor** [comment]
@dregad we can merge these fixes for now.

**Pull request merged**
