### PR TITLE
Custom fields on closing if new status is custom and between resolved and closed

### PR DESCRIPTION
**Pull request by badfiles**

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution

May I kindly ask you, when submitting pull requests, to do so from a branch which is *rebased* on top of mantisbt/master ? You're apparently keeping your local master branch up-to-date with merges, which pollutes the pull request.

Also, we like to keep track of things in our bugtracker, so the normal submission process would be to 

1. open an issue at https://mantisbt.org/bugs/ 
2. fix the issue, referencing it in your commit message (i.e. `Fixes #xxxx`)
3. submit the pull request
4. reference the pull request in the issue

Finally, about the commit message:
- a couple typos: *custom*, not ccustom; and you probably meant *resolved* not resolver. 
- wrap lines at 72 chars
- Maybe the wording could be improved (assuming I understood your issue correctly):

    ```
If a custom status is between resolved and closed, the custom fields
required to resolve a bug should be displayed.
```

Other than that, I'm OK with this change.

**Comment by atrol** [comment]
The issue is there https://www.mantisbt.org/bugs/view.php?id=20004

**Comment by dregad** [comment]
I saw that, but it's not referenced in the commit, so I just repeated the whole process.

**Comment by badfiles** [comment]
@dregad, thanks for the advice.
I'm aware of my poor git experience.
I tried to get rid of my master branch pollution, I've read some manuals, done some experiment but have not succeed. Would you give me a hint, maybe?
As for wired wording and typos, was in a hurry, sorry about that.

**Comment by dregad** [comment]
@badfiles You can issue the following commands in your local repository, assuming that
- you don't have anything in your local master branch that you'd want to keep
- *upstream* remote is mantisbt/mantisbt, *origin* is badfiles/mantisbt

```
git fetch upstream
git checkout master
git reset --hard upstream/master
git push --force origin master
```

The first 3 commands will retrieve the current state of our master branch and align your local branch to it (the *--hard* option makes it drop all of your changes in the process); the last one will update your Github fork (the *--force* option is required to overwrite the changes following use of *--hard* before).

You might then consider making *upstream* the default reference for the master branch, to make your life easier later on
```
git branch --set-upstream-to=upstream/master
```

And since you can't push to mantisbt/mantisbt, set the push url to your own fork
```
git remote set-url --push upstream https://github.com/badfiles/mantisbt
```

Then, to check differences between your master branch vs upstream and update it if needed, you can simply do (example with my own local repo)
```
$ git status
On branch master
Your branch is behind 'upstream/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean

$ git pull
Updating 1c18e71..0616d4f
Fast-forward
 core/custom_function_api.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

$ git status
On branch master
Your branch is up-to-date with 'upstream/master'.
nothing to commit, working directory clean

$ git push
To https://github.com/dregad/mantisbt
   9cb2f40..0616d4f  master -> master
```

After doing that, you might want to rebase your feature branch(es) to the now up-to-date master, and update your pull requests

```
git rebase master feature1
git push --force
```

Hope this helps. Let me know if you need more help, feel free to ping me on Gitter [Gitter](https://gitter.im/mantisbt/mantisbt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by vboctor** [comment]
:+1:

**Comment by badfiles** [comment]
Done

**Comment by badfiles** [comment]
Will you please merge this one, it's been almost a year.

**Comment by badfiles** [comment]
Is there a problem with this PR, cause it's been more than a year.

**Pull request merged**
