### PR TITLE
bug #16774 / PR 157 : changing to one config variable and making it more generic

### PR DESCRIPTION
**Pull request by MrBricodage**
As asked a long time ago in https://www.mantisbt.org/bugs/view.php?id=16774 and in https://github.com/mantisbt/mantisbt/pull/157 (that I just closed cause the base branch was wrong)

Values in config_defaults_inc.php are a proposal

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for the PR. I don't have time to review the code at the moment, but I'd like you to review your commit message
- the bug reference is wrong
- the commit needs to describe what it's doing. See [guidelines](https://www.mantisbt.org/wiki/doku.php/mantisbt:git_commit_messages)

**Comment by dregad** [comment]
Looking at your previous PR, I'm not sure why you're saying the base branch was wrong. This being a new feature, *master* is the correct target - 1.2.x only receives bug fixes.

**Comment by MrBricodage** [comment]
Well understood.
I'll provide you in few hours a new PR that respect guidelines, based on master branch.
regards

**Comment by dregad** [comment]
Cheers. Feel free to reopen #157 if that's convenient.

**Pull request closed without merging**
