### PR TITLE
Allowing to have more than one LDAP server, plus several authentication mechanisms

### PR DESCRIPTION
**Pull request by modir**
I haven't heard anything on my issue here: http://mantisbt.org/bugs/view.php?id=9954 so I decided to create directly a pull request. Maybe I get some faster feedback like this.

(The code works but yes, the documentation still needs to be adjusted etc.)

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution. This will require careful review and testing. Before we start, could you kindly *rebase* (not merge) your feature branch on top of latest master so we have a clean state to work with, as your code currently has conflicts.

**Comment by dregad** [comment]
Also, in http://mantisbt.org/bugs/view.php?id=9954#c54485 you mentioned

> I solved several problems at once so we could close several issues here.

Could you please list all the relevant issues that you addressed, so we can eventually take appropriate action as necessary (e.g. link, test, resolve).

> 3) Migrated all the LDAP config parameters into one array.

That makes sense, but in that case please collapse the individual settings into a single global variable in config_defaults_inc.php, initialize that in a single array() declaration (e.g. similar to $g_display_errors) and please rename $g_ldap to `$g_ldap_settings`. Old settings replaced by the array must be marked as obsolete in core/obsolete.php. I also suggest you define and use constants for the array keys.

**Comment by dharmeshkakadia** [comment]
I am not sure how but I have been getting wrong @mentions from this repo for some time now(as shown in the screenshot below). My guess is somebody had entered a wrong email. Can you guys please check?

image

**Comment by xasos** [comment]
Getting the same thing @dharmeshkakadia

**Comment by LewisJEllis** [comment]
As am I, quite annoying, no idea why.

**Comment by atrol** [comment]
Concerning @mentions 
There is nothing we can do, this is a GitHub issue.

**Comment by dregad** [comment]
@dharmeshkakadia @xasos @LewisJEllis as mentioned this is not something we have any control over. I am sorry about the inconvenience. 

I just wrote to Github support to inform them about the issue, hopefully they'll be able to fix it; I will keep you informed when they respond.

**Comment by dregad** [comment]
@dharmeshkakadia @xasos @LewisJEllis Please see below the feedback from Github support

> Hi Damian,
> 
> A comment was made on this issue that mentioned quite a few users. The comment has been removed but those users were subscribed to the PR's/Issues.
> 
> **They will need to click the unsubscribe link in the notifications to remove.**
> 
> Sorry for the trouble on this one!
> 
> Cheers
> Stacey
> 
> > Dear Github Support,
> >
> > Several users reported (see https://github.com/mantisbt/mantisbt/pull/984#issuecomment-271485433 and the next 2 comments) that they have been receiving @mentions from our repository mantisbt/mantisbt for some time.
> >
> > Could you please look into the issue ?
> >
> > Thank you
> > Damien

**Comment by dharmeshkakadia** [comment]
Thanks @dregad. I am going to unsubscribe from current issues. Hopefully it will not happen on any new issues. Cheers !

**Comment by k2152262** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @dentxinho @bieli @tomcarlson @fengkuok @syncguru @diegovice @caribe @fager @pikiel @nikoutel @6run0 @AgnidykhBayky  @sayyidsh @pixelstreamAu @johnms @mikeching @g-taki @benv8nam @stew721 @sayazyi @mamoniem @lezouretalice @suriyaakudolsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @zedxxx @krime @scottmatheina @faviogalvis @vand3rson @like9729 @badfiles @zenithtekla @sureshinde @peterdavehello @netsf @csatwood @miao606 @bitlin @ioroid @supertassu @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @boby75 @lordshell @burningwind  @nospam1961 @planetbrett @gantha @pbcreativesolutions @bastilimbach @ltpgt @modir  @dharmeshkakadia @xasos @LewisJEllis progress on implementing feedback ?

**Comment by sync1** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  whats status ?

**Comment by modir** [comment]
@dregad I was actually following sort of the old naming convention for the variables:

-$g_ldap_server = 'ldaps://ldap.example.com/';
+$g_ldap['server'] = 'ldaps://ldap.example.com/';

I just changed the last part to an array key. But sure. I don't mind calling the array $g_ldap_settings. That's fine for me too

**Comment by vboctor** [comment]
I've recently opened a PR for support for Auth Plugins (#1070).  It would be good to get your feedback on it and identify the missing pieces to be able to move LDAP into its own plugin.  I know for sure we will need an event that validates a username + password pair.  This would connect to LDAP to validate the password and also create the user if needed.

**Comment by modir** [comment]
@vboctor I have already seen it and I wrote a first issue. ;) I plan to rewrite my code to create it as an auth plugin. From my point of view this is the best solution. Important is to make sure that all configuration related to this user is then coming from the same auth plugin.

**Comment by vboctor** [comment]
Sounds good @modir - in the meantime I will close this PR.  Feel free to open feature requests in our tracker for any limitations that get in your way.  My plan is to add more auth plugin events/features as needed.  Ideally, your work will deliver an LDAP Auth Plugin that we can use to replace the core implementation.

**Comment by gerrymantis** [comment]
Any estimate when multiple ldap support will be part of the general mantis release ?

**Comment by kyriehan89** [comment]
hi, is there any update for this?
I need to login using multiple LDAP

**Comment by gerrymantis** [comment]
Hi,  I never received any update.

**Comment by MatthParrot** [comment]
Hello,
Sorry for my english but i want to tell, how I have configure, because it work perfectly ! (version 2.19, so actually the last version.)

I have delete and add line per line the code of differentes files how the creator have commit.

and in the config_inc.php file i have configure the LDAP like this:

`
$g_ldap_port                    = '389';
$g_use_ldap_email               = ON;
$g_validate_email               = OFF;

$g_ldap = array(
        array(
                'organization' => '(objectClass=*)',
                'root_dn' => 'DC=domain1,DC=com1',
                'uid_field' => 'samaccountname',
                'server' => 'LDAP://IP_or_DNSname',
                'network_timeout' => 0,
                'protocol_version' => 3,
                'follow_referrals' => OFF,
                'bind_dn' => 'samaccountname of serviceaccount mantis',
                'bind_passwd' => 'serviceaccount mantis password'
        ),
        array(
                'organization' => '(objectClass=*)',
                'root_dn' => 'DC=domain2,DC=com2',
                'uid_field' => 'samaccountname',
                'server' => 'LDAP://IP_or_DNSname',
                'network_timeout' => 0,
                'protocol_version' => 3,
                'follow_referrals' => OFF,
                'bind_dn' => 'samaccountname of serviceaccount mantis',
                'bind_passwd' => 'serviceaccount mantis password'
        )


);
`

Thank you for your work !!

**Comment by ssorrentino** [comment]
Hi All, i modified all the stuff as indicated, added also the the instruction posted from @MatthParrot but seems that doesn´t work.....how i can check what is wrong? i use the Mantis v 2.22.

**Comment by modir** [comment]
a) my client moved away from mantis so the code was never updated to newer versions.
b) This is a pull request and not an issue tracker.
The only help I can offer at the moment is to look in the log files and to set the highest log level:
https://www.mantisbt.org/docs/master/en-US/Admin_Guide/html/admin.config.logging.html
Maybe you find then there more infos about what went wrong.

**Comment by starikov-aa** [comment]
Here is my implementation. Has been in use for six months, no problems.

https://github.com/starikov-aa/Mantis-MultiLdapAuth

**Comment by gerrymantis** [comment]
Thank you for sharing starikov-aa.

I gave up hope and did it the hard way – combined domains.

From: starikov-aa ***@***.***>
Sent: Sunday, July 4, 2021 10:40 PM
To: mantisbt/mantisbt ***@***.***>
Cc: Brennan, Gerard A ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [mantisbt/mantisbt] Allowing to have more than one LDAP server, plus several authentication mechanisms (#984)


Here is my implementation. Has been in use for six months, no problems.

https://github.com/starikov-aa/Mantis-MultiLdapAuth

**Pull request closed without merging**
