### PR TITLE
Fix attachments when notes are private by default

### PR DESCRIPTION
**Pull request by vboctor**
Fixes #26805

### CODE REVIEW

**Comment by atrol** [comment]
No need for an additional PR as there is already a fix for it in PR https://github.com/mantisbt/mantisbt/pull/1606

**Comment by vboctor** [comment]
@atrol I think this current PR should be targeted for `2.24.1` and #1606 targeted for `2.25.0`.

**Comment by vboctor** [comment]
@atrol are you ok with this?

**Comment by atrol** [comment]
> @atrol are you ok with this?

I am.
I wanted  to be sure that other devs are aware of the other open PR where we might get merge conflicts after this change.

**Pull request merged**
