### PR TITLE
[WIP] Fix add monitor regressions

### PR DESCRIPTION
**Pull request by atrol**
Fixes #33404
Fixes #33348

### CODE REVIEW

**Comment by dregad** [comment]
@atrol considering the discussion in https://mantisbt.org/bugs/view.php?id=33404, particularly @vboctor's last note, I thought I should merge this PR but then I noticed you set it as _Draft_, not sure what is the reason for that. Let me know if this is OK to merge or if you are still working on it.

**Comment by atrol** [comment]
As mentioned at https://mantisbt.org/bugs/view.php?id=33404#c68390
After the change proposed by Victor (currently implemented in this WIT PR), we are back to where we have been in 2.25.8.
This means you are able to add users without access to private issues to the monitoring list, but after that, the added user is not able to access the issue.
@dregad @vboctor isn't the current 2.26.0 behaviour better than what we had in 2.25.8?

**Comment by vboctor** [comment]
I think we should merge the fix. The fix addresses case where users being added would have access to the issue, but were not being able to be added. If there are other corner cases we need to address, we should open an issue with exact repro steps and discuss if we can address that without breaking valid functionality. I think the fix should be part of 2.26.1.

**Comment by atrol** [comment]
> The fix addresses case where users being added would have access to the issue, but were not being able to be added. 

@vboctor seems I have not the right configuration for such a case. Which settings are needed to get it?

**Pull request merged**
