### PR TITLE
Issue #21659 fix for PHP Parse error

### PR DESCRIPTION
**Pull request by jenolan**
syntax error, unexpected 'version' (T_STRING) in browser_search_plugin.php on line 56

### CODE REVIEW

**Comment by syncguru** [comment]
👍

**Comment by atrol** [comment]
👍

**Comment by vboctor** [comment]
It is unclear to me why the changed code is different from the old code and why it fixes the issue?  It seems that we are outputing exactly the same output but form PHP instead of inline code.

**Comment by grangeway** [comment]
Victor, you can use <? as "Short tags" in php ( the short_open_tag config option), so in this case, php is trying to parse the string as php code

**Comment by vboctor** [comment]
Merged via 1b32685bfd2a82fe53848686dd393b46276ae622 in 1.3.x and will be merged into master as part of regular merges.  Thanks @jenolan

**Pull request closed without merging**
