### PR TITLE
Change view issue menu to allow plugin links

### PR DESCRIPTION
**Pull request by cproensa**
Changed the style of the upper menu in bug view page, to allow the
correct formatting of links provided by plugins with EVENT_MENU_ISSUE.

This event may return a prepared html link, which was being shown as a
bracketed plain link (old style)
The new style introduced by new ui, used link buttons, but the function
provided to print abutton from the event return (print_small_button),
must provide a separated urn and label, which is not possible with an
already prepared html link.

The changed style now uses list items that formats the link html "as
is" in an uniform way with the ui.

Fixes: #21559

### CODE REVIEW

**Comment by cproensa** [comment]
before:
seleccion_073

after:
seleccion_074

**Comment by vboctor** [comment]
Haven't reviewed the change yet.  But the new buttons look disabled?

**Comment by cproensa** [comment]
updated with one case i forgot to change.

>  But the new buttons look disabled?
These are the list styles for manage navigation bar.

The substitution for buttons was made as part of the rewrite, and it can be refined.
I think semantically these links are better suited as list items, and it solves the issues mentioned with the plugin event links, thats a fine combo.

@syncguru could you provide a more stylish class for LI items to be used in this situation?

**Comment by vboctor** [comment]
For plugins, as part of changes done to modern UI we no longer want to accept pre-formatted links.  The plugins provide an associative arrive that provides information like:

- URL
- Label
- Icon (based on font-awesome)

Then the core code does the right thing in terms of formatting to match the core UI.  It is a change from what we had for 1.3 plugins, but it provides more power and flexibility going forward.

**Comment by cproensa** [comment]
I disagree that the UI core should format these as buttons.
They are links, and are more properly rendered as list items. 

>  It is a change from what we had for 1.3 plugins

Then it's not fully implemented, still, as you can see in https://www.mantisbt.org/bugs/view.php?id=21559
the worng format is still being printed

**Pull request closed without merging**
