### PR TITLE
Russian translations bulk update

### PR DESCRIPTION
**Pull request by dregad**
Contributed by Alexey Chumakov (@achumakov)

Fixes #20531

### CODE REVIEW

**Comment by dregad** [comment]
As per @siebrand's request in https://www.mantisbt.org/bugs/view.php?id=20531

**Comment by badfiles** [comment]
quotes should also be Russian, and a native speaker (other than author) review is required, I guess.

**Comment by siebrand** [comment]
@badfiles changes can be reviewed at translatewiki.net.

**Comment by siebrand** [comment]
It looks like every line in the file was replaced from the patch statistics. That's susicious, and most of the time points to a change in line breaks. Please fix that.

**Comment by siebrand** [comment]
It also looks like the header copyright year was changed back from 2016 to 2014. But as the patch is so large, that github doesn't display a diff, I cannot assess additional formatting issues.

**Comment by dregad** [comment]
@siebrand fixed line endings.

**Pull request merged**
