### PR TITLE
Improve UX & consistency for inline action icons

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #25905

Before:
delete-tag

email-reporter

image-actions

Screen Shot 2019-08-19 at 7 30 54 PM

After:
Screen Shot 2019-08-19 at 7 24 33 PM

Screen Shot 2019-08-19 at 7 26 19 PM

Screen Shot 2019-08-19 at 7 25 18 PM

Screen Shot 2019-08-19 at 7 35 19 PM

Screen Shot 2019-08-19 at 7 33 20 PM

### CODE REVIEW

**Comment by vboctor** [comment]
@syncguru can you please rebase on master.

**Comment by syncguru** [comment]
@vboctor done. 
I think the new markup is breaking travis-ci validation.

**Comment by cproensa** [comment]
Files that don't have a preview are shown differently, at least: different padding for the attachement element. They look skewed when compared.
I'm not sure if not having a lighter background box is intended (as not having a preview).

imagen

other impressions:
- I feel the collapse arrow is a bit too close to the filenames/size text .
- And i tend to go to click in the empty space between the arrow and the trashcan, as expecting that it would also expand the preview (but only the arrow is clickable to expand)
- some kind of hover effect for the attachment area? it would help when aiming for the right trashcan on several stacked attachments.
- The whole horizontal area for the attachment looks too wide/narrow in a full screen. But this is a general layout issue, not specific to this PR. However, it can be bad when the trashcan icon is so far to the right that it gets lost. Maybe some limitation in the grid for lg, xl widths can be applied?

**Comment by syncguru** [comment]
@cproensa:
> Files that don't have a preview are shown differently

Good catch

> I'm not sure if not having a lighter background box is intended

Yes, it is intended and so it addresses your need of a hover of the raw

>I feel the collapse arrow is a bit too close to the filenames/size text

Will add more spacing


@dregad:
> I don't see the benefit of putting the trashcan to the right

I am not sure how much use `delete` action gets. I suspect that most of the usage is for expanding and collapsing the preview. Having a `delete` very close to expand\collapse felt like giving prominence to unlikely action which can easily be clicked by mistake due to proximity. Happy to revert it back but I thought I should present my case first.

> we're not deleting the tag, just detaching it from the issue

Good point. I will switch back. I have a bigger change to tagging in the works so I will defer any improvements until then.

**Comment by cproensa** [comment]
> I am not sure how much use delete action gets. I suspect that most of the usage is for expanding and collapsing the preview. Having a delete very close to expand\collapse felt like giving prominence to unlikely action which can easily be clicked by mistake due to proximity.

I also dont like it placed next to the expand icon.
That's why i though of reducing the width of the boxes, so the icon is still at the right side, but is easier to locate it visually.

> Yes, it is intended and so it addresses your need of a hover of the raw

The hover suggestion was related to having the thrash icon so far to the right. If the box is more compact, that would not be necessary because everything is more focused in the field of view

**Comment by syncguru** [comment]
> If the box is more compact
Since we preview the image inline (in the expanded block), making the box compact will reduce the preview space. If we move the image prereview to something like lightbox, then attachments could be just a series of small boxed lined beside each other.

**Comment by cproensa** [comment]
>  If we move the image prereview to something like lightbox, then attachments could be just a series of small boxed lined beside each other.

The "inline" placing of boxes would be more compact. Slightly, resembling, the dropzone way of placing attachment boxes.
But i'm not suggesting going to that extreme. You are right, that a narrow box limits the preview space. In this scenario i was thinking of the boxes still being one per row, but the box is expanded to full width when the preview is enabled

**Comment by syncguru** [comment]
@dregad ping.

**Comment by dregad** [comment]
@syncguru sorry for the delayed response.

>> I don't see the benefit of putting the trashcan to the right
>
> [...] I suspect that most of the usage is for expanding and collapsing the preview. 

That's probably true.

> Having a delete very close to expand\collapse felt like giving prominence to unlikely action which can easily be clicked by mistake due to proximity. 

Fair enough, but while this layout if fine on smaller screens, on a "normal" one (say, 1280x1024) with a maximized browser window, the trashcan icon is too far on the right, making it feel "disconnected" from the attachment in my opinion.

image

I stand by my preference for having it closer to the other controls, but considering that I seem to be in minority here since @cproensa agrees with your perspective, I guess I'll learn to live with it :wink:.


Before the PR can be merged, please **REBASE** it on top of latest master and resolve the conflicts. Kindly note that merging is not equivalent as we try to maintain a more linear Git history.

**Comment by syncguru** [comment]
Thanks, @dregad - rebase is done.

**Comment by dregad** [comment]
Thanks. This pull request has been integrated manually.

**Pull request merged**
