### PR TITLE
misc. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Some are doxy comments, some are non-user-facing.

### CODE REVIEW

**Comment by atrol** [comment]
Files in folder library/utf8 should not be changed as this is 3rd party code from https://sourceforge.net/projects/phputf8/files/phputf8/

**Comment by luzpaz** [comment]
Removed all library/utf8 files

**Comment by atrol** [comment]
> Removed all library/utf8 files

Seems something went wrong.
https://github.com/mantisbt/mantisbt/pull/1152/files
Now I see just changes in library/utf8.

**Comment by luzpaz** [comment]
sorry my git-fu skills are sucking ATM.

**Pull request closed without merging**
