### PR TITLE
Update mc_issue_api.php

### PR DESCRIPTION
**Pull request by dwings**
Fix to make this work with the REST API

### CODE REVIEW

**Comment by dregad** [comment]
Please link this to an issue in our bugtracker, describing what the problem is

**Comment by vboctor** [comment]
@dwings please also make sure that the change doesn't negatively impact SOAP API.

**Comment by elmarculino** [comment]
There is already an issue in the bugtracker [23264](https://www.mantisbt.org/bugs/view.php?id=23264) and a PR #1174 for this bug.

**Comment by vboctor** [comment]
Merged via a1b8718b0c64b1f1292ecb8da15cbf1415a62b99

**Pull request closed without merging**
