### PR TITLE
Don't show "Upgrade Your Installation" when switching admin bar tabs

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #21602

### CODE REVIEW

**Comment by dregad** [comment]
I think adding a comment indicating why schema.php has to be included in each of these files would be useful, since it is *a priori* unrelated to the task at hand.

**Comment by syncguru** [comment]
@dregad Comment added.

**Comment by dregad** [comment]
Thanks. :+1:

**Comment by vboctor** [comment]
:+1:

**Comment by vboctor** [comment]
Merged via 2a64d17673329e0897acecc3f56e21ffcc9405b5

**Pull request closed without merging**
