### PR TITLE
display attachments section in bug view

### PR DESCRIPTION
**Pull request by shaozi**
fix issue https://www.mantisbt.org/bugs/view.php?id=22323

### CODE REVIEW

**Comment by atrol** [comment]
Didn't have a deeper look, but there are
- quite a lot of changes that are not related to https://www.mantisbt.org/bugs/view.php?id=22323
- merge conflicts

**Comment by dregad** [comment]
@shaozi please update the PR so it can be reviewed. Thank you.

**Comment by shaozi** [comment]
This pull request is submitted to upstream by error. Please reject it.

**Comment by shaozi** [comment]
submitted by mistake.

**Pull request closed without merging**
