### PR TITLE
New password activation

### PR DESCRIPTION
**Pull request by cproensa**
Manage the password reset hash as a token.
Refactor verify.php to be a not-logged-in page, like login_page.php, so the only action the user can do is change the password, and not navigate into the site.
If the user does not change the password and quits tue page, the activation token is still valid until the change is effectively done (or token timeout)

Fix #0020686, #0006009

### CODE REVIEW

**Comment by dregad** [comment]
Tested the proposed code OK.
+1

**Comment by cproensa** [comment]
@dregad
I have some doubts if it works fine with LDAP authentication, where the user activation does not use a user provided password. I cannot test with a LDAP now, so i'd appreciate feedback on this

**Comment by dregad** [comment]
I don't have a live LDAP setup either, sorry.

**Comment by cproensa** [comment]
I have tested LDAP with the $g_ldap_simulation_file_path option
Seems OK, as i made the adjustments to not show the password form if the user is not able to change, and show the proper warning. However, the reset password option is not available in the first place, when using LDAP mode.

**Comment by dregad** [comment]
Merged in d7b8d33e79250e67888e2d6e82ee1e5f2bfd091f, thank you @cproensa

**Pull request closed without merging**
