### PR TITLE
Import missing settings from ./config_defaults_inc.php

### PR DESCRIPTION
**Pull request by g0tmi1k**
Looking at `./config_defaults_inc.php`
Then comparing whats in DocBook's XML

This then takes the variables and their comments and imports them.

```console
github/mantisbt % HEADER=""
TMP=""

grep -E '^(\$g_|# .* #)' ./config_defaults_inc.php \
  | while read -r LINE; do
    case ${LINE} in
      #* )
        TMP=$( echo "${LINE}" | sed -E 's/ ?# ?//g' );
        if [ "${TMP}" != "${HEADER}" ]; then
          HEADER="${TMP}"
          echo ""
          echo "## ${HEADER}"
        fi
        ;;
      \$g*)
        VAR="$( echo ${LINE} | awk '{print $1}' )"
        grep -qR "<term>${VAR}</term>" ./docbook/Admin_Guide/en-US/config \
          || echo "MISSING ${VAR}"
        ;;
      *)
        echo "ISSUE with: ${LINE}"
        ;;
    esac
  done

## MantisBT Database Settings
MISSING $g_dsn

## Folder Locations
MISSING $g_vendor_path

## MantisBT Path Settings

## Web Server

## Security and Cryptography

## Signup and Lost Password

## Anti-Spam

## MantisBT Email Settings
MISSING $g_show_user_realname_threshold

## MantisBT Version String
MISSING $g_version_suffix
MISSING $g_copyright_statement

## MantisBT Language Settings
MISSING $g_language_auto_map

## MantisBT Font Settings

## MantisBT Display Settings
MISSING $g_admin_checks
MISSING $g_filter_position
MISSING $g_action_button_position
MISSING $g_sort_by_last_name
MISSING $g_show_changelog_dates
MISSING $g_show_roadmap_dates

## MantisBT Time Settings

## MantisBT Date Settings

## MantisBT TimeZone Settings

## MantisBT News Settings

## MantisBT Default Preferences
MISSING $g_default_bug_relationship_clone
MISSING $g_default_bug_relationship
MISSING $g_show_sticky_issues
MISSING $g_default_email_on_new
MISSING $g_default_email_on_assigned
MISSING $g_default_email_on_feedback
MISSING $g_default_email_on_resolved
MISSING $g_default_email_on_closed
MISSING $g_default_email_on_new_minimum_severity
MISSING $g_default_email_on_assigned_minimum_severity
MISSING $g_default_email_on_feedback_minimum_severity
MISSING $g_default_email_on_resolved_minimum_severity
MISSING $g_default_email_on_closed_minimum_severity
MISSING $g_default_email_on_reopened_minimum_severity
MISSING $g_default_email_bugnote_limit

## MantisBT Summary Settings

## MantisBT Bugnote Settings

## MantisBT Bug History Settings

## MantisBT Reminder and Mention Settings

## MantisBT Sponsorship Settings

## MantisBT File Upload Settings
MISSING $g_attachments_file_permissions
MISSING $g_document_files_prefix
MISSING $g_absolute_path_default_upload_folder

## MantisBT HTML Settings
MISSING $g_html_valid_tags_single_line
MISSING $g_max_dropdown_length
MISSING $g_wrap_in_preformatted_text

## MantisBT Authentication and LDAP Settings

## Status Settings
MISSING $g_bug_readonly_status_threshold
MISSING $g_bug_closed_status_threshold

## Bug Attachments Settings
MISSING $g_preview_max_width
MISSING $g_preview_max_height
MISSING $g_view_attachments_threshold
MISSING $g_download_attachments_threshold
MISSING $g_delete_attachments_threshold
MISSING $g_allow_view_own_attachments
MISSING $g_allow_download_own_attachments
MISSING $g_allow_delete_own_attachments

## Field Visibility

## MantisBT Misc Settings
MISSING $g_view_bug_threshold
MISSING $g_update_bug_assign_threshold
MISSING $g_private_bugnote_threshold
MISSING $g_view_handler_threshold
MISSING $g_view_history_threshold
MISSING $g_bug_reminder_threshold
MISSING $g_upload_project_file_threshold
MISSING $g_upload_bug_file_threshold
MISSING $g_add_bugnote_threshold
MISSING $g_update_bugnote_threshold
MISSING $g_view_proj_doc_threshold
MISSING $g_manage_site_threshold
MISSING $g_manage_project_threshold
MISSING $g_manage_news_threshold
MISSING $g_delete_project_threshold
MISSING $g_create_project_threshold
MISSING $g_private_project_threshold
MISSING $g_project_user_threshold
MISSING $g_delete_bugnote_threshold
MISSING $g_move_bug_threshold
MISSING $g_stored_query_use_threshold
MISSING $g_stored_query_create_threshold
MISSING $g_stored_query_create_shared_threshold
MISSING $g_update_readonly_bug_threshold
MISSING $g_view_changelog_threshold
MISSING $g_roadmap_view_threshold
MISSING $g_roadmap_update_threshold
MISSING $g_update_bug_status_threshold
MISSING $g_reopen_bug_threshold
MISSING $g_report_issues_for_unreleased_versions_threshold
MISSING $g_set_bug_sticky_threshold
MISSING $g_set_status_threshold
MISSING $g_allow_no_category
MISSING $g_limit_reporters
MISSING $g_limit_view_unless_threshold
MISSING $g_allow_reporter_upload
MISSING $g_bug_count_hyperlink_prefix
MISSING $g_default_manage_tag_prefix

## MantisBT Look and Feel Variables
MISSING $g_status_colors
MISSING $g_display_bug_padding
MISSING $g_display_bugnote_padding

## MantisBT Cookie Variables
MISSING $g_string_cookie
MISSING $g_project_cookie
MISSING $g_view_all_cookie
MISSING $g_collapse_settings_cookie
MISSING $g_manage_users_cookie
MISSING $g_manage_config_cookie
MISSING $g_logout_cookie
MISSING $g_bug_list_cookie

## MantisBT Filter Variables
MISSING $g_view_filters
MISSING $g_use_dynamic_filters

## MantisBT Enum Strings
MISSING $g_access_levels_enum_string
MISSING $g_project_status_enum_string
MISSING $g_project_view_state_enum_string
MISSING $g_view_state_enum_string
MISSING $g_priority_enum_string
MISSING $g_severity_enum_string
MISSING $g_reproducibility_enum_string
MISSING $g_status_enum_string
MISSING $g_resolution_enum_string
MISSING $g_projection_enum_string
MISSING $g_eta_enum_string
MISSING $g_sponsorship_enum_string
MISSING $g_custom_field_type_enum_string

## MantisBT Speed Optimisation

## Include files

## Redirections
MISSING $g_logout_redirect_page

## Headers

## Custom Fields
MISSING $g_custom_field_edit_after_create

## Custom Menus

## Icons
MISSING $g_file_type_icons
MISSING $g_file_download_content_type_overrides
MISSING $g_status_icon_arr
MISSING $g_sort_icon_arr

## My View Settings

## RSS Feeds
MISSING $g_rss_enabled

## Bug Relationships
MISSING $g_backward_year_count
MISSING $g_forward_year_count
MISSING $g_custom_group_actions

## Wiki Integration

## Recently Visited
MISSING $g_recently_visited_count

## Bug Tagging!!!
MISSING $g_tag_separator
MISSING $g_tag_view_threshold
MISSING $g_tag_attach_threshold
MISSING $g_tag_detach_threshold
MISSING $g_tag_detach_own_threshold
MISSING $g_tag_create_threshold
MISSING $g_tag_edit_threshold
MISSING $g_tag_edit_own_threshold

## Time tracking

## Profile Related Settings
MISSING $g_enable_profiles
MISSING $g_add_profile_threshold
MISSING $g_manage_global_profile_threshold
MISSING $g_allow_freetext_in_profile_fields

## Plugin System
MISSING $g_plugins_enabled
MISSING $g_plugin_path
MISSING $g_manage_plugin_threshold
MISSING $g_plugin_mime_types
MISSING $g_plugins_force_installed

## Due Date

## Sub-projects

## Debugging / Developer Settings

## Configuration Settings

## Webservice Configuration
MISSING $g_webservice_priority_enum_default_when_not_found
MISSING $g_webservice_severity_enum_default_when_not_found
MISSING $g_webservice_status_enum_default_when_not_found
MISSING $g_webservice_resolution_enum_default_when_not_found
MISSING $g_webservice_projection_enum_default_when_not_found
MISSING $g_webservice_eta_enum_default_when_not_found
MISSING $g_webservice_error_when_version_not_found
MISSING $g_webservice_version_when_not_found

## Issue Activities
github/mantisbt %
github/mantisbt % !! | grep -c MISSING
143
github/mantisbt %
```

### CODE REVIEW

**Comment by g0tmi1k** [comment]
This was the dirty bash that gave some help:

```shell
HEADER=""
TMP=""
COMMENT=""

grep -E '^(# .* #|\$g_.*|\s\*\s.*)?$' ./config_defaults_inc.php \
  | while read -r LINE; do
    case "${LINE}" in
      #* ) 
        COMMENT=""
        TMP=$( echo "${LINE}" | sed -E 's/ ?# ?//g' );
        if [ "${TMP}" != "${HEADER}" ]; then
          HEADER="${TMP}"
          echo ""
          echo "## ${HEADER}"
        fi
        ;;
      "")
        COMMENT=""
        ;;
      \$g*)
        VAR="$( echo ${LINE} | awk '{print $1}' )"
        grep -qR "<term>${VAR}</term>" ./docbook/Admin_Guide/en-US/config \
          && continue;

          if [ -z "${COMMENT}" ] || \
             [ "${COMMENT}" = "'any'" ]; then
            COMMENT="TODO"
          fi

        echo """\t\t<varlistentry>
\t\t\t<term>${VAR}</term>
\t\t\t<listitem>
\t\t\t\t<para>${COMMENT}</para>
\t\t\t</listitem>
\t\t</varlistentry>"""

COMMENT=""
        ;;
      *)
        echo "${LINE}" | grep -q '^* @global' \
          && continue

        if [ -n "$COMMENT" ]; then
          COMMENT="${COMMENT}\n\t\t\t\t\t$( echo ${LINE} | sed 's/^\* //' )"  
        else
          COMMENT="${COMMENT}$( echo ${LINE} | sed 's/^\* //' )"
        fi
        ;;
    esac
  done
```

**Comment by dregad** [comment]
Thanks for your contribution !

**Comment by g0tmi1k** [comment]
You are welcome @dregad .
Thanks for the merge <3

**Comment by g0tmi1k** [comment]
Is there any plans on updating: https://www.mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/

Ive just seen that v2.26 was released.
Looking on that page, its for "MantisBT 2.0" and the copyright is "2016".

**Pull request merged**
