### PR TITLE
Fix #0020275

### PR DESCRIPTION
**Pull request by tgulacsi**
form_api.form_security_token returns constant 1 if p_security_token is
not null.

### CODE REVIEW

**Comment by dregad** [comment]
You're right, not sure what I was thinking.

**Comment by dregad** [comment]
Fixed in 419756478a7b154e5f95b6a71259f01a16b47ff5

**Comment by dregad** [comment]
Unfortunate typo in issue reference...

**Comment by tgulacsi** [comment]
Sorry :)
(I had to look three times at the  "changed the title ..." line to see the difference...(

**Comment by dregad** [comment]
I said unfortunate, because it triggered a bug causing the *My View* page to error out at http://mantisbt.org/bugs :fearful:

**Pull request closed without merging**
