### PR TITLE
Adding In-Reply-To header to bugnote notification email

### PR DESCRIPTION
**Pull request by sederther**
Regarding issue https://www.mantisbt.org/bugs/view.php?id=32038

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
Thanks for your contribution. Looking good but have not had time to actually test it yet. Just a few minor comments...

**Comment by sederther** [comment]
I have added a commit about the requested changes.

**Review by dregad — APPROVED** [review]

**Comment by dregad** [comment]
Fixed in fd4b1c56ed9cc7d7f51603c0aacea285ebb3794d

**Comment by dregad** [comment]
Thanks @sederther

**Pull request closed without merging**
