### PR TITLE
Rebrands to "Bugger"

### PR DESCRIPTION
**Pull request by unt01d**
Just feel like you're missing a trick here.

If Git has taught us anything, it's that software named after a mild British curse word is destined for greatness.

### CODE REVIEW

**Comment by atrol** [comment]
Weak joke,

**Comment by unt01d** [comment]
Yeah, fair comment  :)

**Comment by unt01d** [comment]
Is it because I went with Comic Sans for the logo?

**Comment by dregad** [comment]
🙄

**Pull request closed without merging**
