### PR TITLE
additions to api soap, user add, sub projects (#0010349)

### PR DESCRIPTION
**Pull request by wepl**
new functions to add user and assign to sub projects

### CODE REVIEW

**Comment by nghianguyendev** [comment]
Hi,

I tried the api from my asp.net web site and got the error message :

"Procedure 'mc_account_add' not present"

the function is listed in my service reference and accessed to it successful, but at runtime it raise the error : "Procedure 'mc_account_add' not present"

I greatly appreciate any help.
Thanks

**Comment by atrol** [comment]
@nghianguyendev
maybe the same problem that stovocor mentioned:
The WSDL is cached.

**Comment by nghianguyendev** [comment]
@atrol 
Please help me how to clear cache, i used apache server for mantis and client in asp.net.
I get the error on the first time calling the mantis soap api from asp.net
Thanks

**Comment by atrol** [comment]
http://lmgtfy.com/?q=how+to+clear+php+wsdl+cache

**Comment by skeyby** [comment]
Hello, is there any plan to merge this in the main tree?

Thanks.

**Comment by dregad** [comment]
If we're lucky, @rombert our resident SOAP API expert will comment on that one ;)

**Comment by rombert** [comment]
Shamefully, my last comment from two years ago was 

> Thanks, I'll review this over the weekend and try to add the tests myself.

@skeyby  - have you tried this PR yourself to validate that the changes do what is expected?

**Comment by dregad** [comment]
> Shamefully, my last comment from two years ago was
>> Thanks, I'll review this over the weekend and try to add the tests myself.

... then real life got in the way :-P

**Comment by rombert** [comment]
> ... then real life got in the way :-P

That, and I also have a lousy memory :-)

FTR, I'll review this for inclusion into master, not master-1.2.x .

**Comment by skeyby** [comment]
@rombert yes, we basically tried mc_account_add and seems to be working ok.

**Comment by skeyby** [comment]
@rombert OK. I just hand-merged the diff into master on a new installation. Tomorrow morning we'll do a few test on it as well.. Will give you a feedback.

**Comment by skeyby** [comment]
Hello @rombert,

just wanted to tell you we tried:
* mc_account_add
* mc_account_delete
* mc_project_set_user_access

on our local testing instance and all three apprently worked ok. We didn't dig in the DB to do insight checking, but the WEB interface correctly reflect the changes; I'm pretty confident the patches are ok.

**Comment by atrol** [comment]
Unfortunately there is the open issue https://www.mantisbt.org/bugs/view.php?id=12328
"Normalise access checks between the web interface and the SOAP API"

Until this is fixed, we should ensure that the SOAP API uses the exact same security settings that the web interface uses.

E.g. 
- do not check for mci_has_administrator_access, but for having manage_user_threshold, manage_project_threshold, project_user_threshold, ... rights.
- ensure that we don't delete the last administrator account
...

Keep in mind that mci_has_administrator_access just checks for webservice_admin_access_level_threshold where MANAGER is the default.
The current implementation would allow the MANAGER of a single project to delete all users including all ADMINISTRATOR accounts!

I could accept mci_has_administrator_access at the moment if webservice_admin_access_level_threshold is set to ADMINISTRATOR.
Independant from that, deleting the last administrator account should certainly be prevented (see manage_user_delete.php)

@rombert, what do you think?

**Comment by rombert** [comment]
@atrol is correct in pointing out that we need some more checks for `mc_account_add` and `mc_account_delete`. 

The current rules are encoded in [manage_user_create.php](https://github.com/mantisbt/mantisbt/blob/74b42afc1dfa957e3a90106a126d7840a21cd4d2/manage_user_create.php) and [manage_user_delete.php](https://github.com/mantisbt/mantisbt/blob/74b42afc1dfa957e3a90106a126d7840a21cd4d2/manage_user_delete.php), and they must be respected in the SOAP API as well.

I understand it's not necessarily simple to extract a common piece of code which works for the SOAP API and for the web part as well, so until [bug 12328](https://www.mantisbt.org/bugs/view.php?id=12328) is done I will not oppose the duplication of checks, but these checks must be added to the SOAP API as well

**Comment by atrol** [comment]
Forgot to mention that there is also no validation of $p_user['email'] in terms of email_ensure_not_disposable().

**Comment by l266509** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  Whats status of this PR?

**Pull request closed without merging**
