### PR TITLE
Optimize vertical space in "My View" page

### PR DESCRIPTION
**Pull request by syncguru**
Fixes #21123

Before:
screen shot 2016-08-15 at 7 32 27 pm

After:
screen shot 2016-08-15 at 7 30 27 pm

### CODE REVIEW

**Comment by vboctor** [comment]
How about adding a link icon after the issue count?

Here is the URL for the icon
http://fontawesome.io/icon/link/

**Comment by dregad** [comment]
I'm fine with removing the table's footer which does not add any value, but is it really necessary to add a burger icon with a menu that only provides a link which is already existing ?

I would propose to remove the menu, leaving only the link on the table's title. If you do add the link icon per victor's suggestion, IMO it would be better to have it next to the link (i.e. *before* the issue count, not after)

**Comment by atrol** [comment]
What about using the icon on the left top of the box (change fa-list-alt to fa-link) for the link?

**Comment by syncguru** [comment]
@vboctor - too busy for table header
@atrol - that's anti-pattern

**Comment by syncguru** [comment]
Updated the PR, here is how it looks now:

screen shot 2016-08-21 at 12 31 44 pm

**Comment by vboctor** [comment]
:+1:

**Comment by vboctor** [comment]
Merged via 5de037c326d550535afad3288c72bf9876439630

**Pull request closed without merging**
