### PR TITLE
Add release marker for database schema

### PR DESCRIPTION
**Pull request by atrol**
Fixes [#34813](https://mantisbt.org/bugs/view.php?id=34813)

### CODE REVIEW

**Review by vboctor — APPROVED** [review]
Do we really need a bug or even a PR for adding a comment line? I suggest deleting the bug.

**Comment by dregad** [comment]
> Do we really need a bug or even a PR for adding a comment line? I suggest deleting the bug.

I agree on principle - I would personally have committed the fix directly without a PR. Regarding the Issue, it was created by a user so we should not delete it.

**Review by dregad — APPROVED** [review]

**Comment by vboctor** [comment]
@dregad @atrol I missed the fact that a user reported this. Makes sense.

**Comment by atrol** [comment]
@dregad @vboctor right, PR is a bit overhead, I will push such small changes without asking next time.

Having linked issues to commits should be a must in my opinion, even if there is none created by external users.
I am also working on some products where I configured branch policies for master and release branches.
No one is allowed to push to these branches without having a linked work item.
Most of the team members like it, especially the ones that have to deal with fixing regressions and writing test cases for such fixes.

**Pull request merged**
