### PR TITLE
Rest API issue relationship add/delete fixes

### PR DESCRIPTION
**Pull request by dregad**
- fixing errors
- code cleanup
- add unit tests

Fixes [#32835](https://mantisbt.org/bugs/view.php?id=32835)

Planning to back port the fixes to 2.25.x

### CODE REVIEW

**Review by vboctor — APPROVED** [review]
Looks good. Nice cleanup!

You could add two more tests if you like:
- The reversing of relationship logic, not sure if this exercised or not.
- Attempting to resolve an issue that has non-resolved children.

**Comment by dregad** [comment]
Thanks for the review.

> You could add two more tests if you like:
> 
> * The reversing of relationship logic, not sure if this exercised or not.

This is probably covered by the existing test, as it basically the same as replacing an existing relationship, but I'll have a closer look to make sure.

> * Attempting to resolve an issue that has non-resolved children.

Good one, didn't think about it. Will add.

**Comment by dregad** [comment]
> > * Attempting to resolve an issue that has non-resolved children.
> 
> Good one, didn't think about it. Will add.

As it turns out, **the test should fail but does not**: the API will happily set the issue to *resolved*. So we have a discrepancy between _mc_issue_update()_ and _bug_update.php_ - and quite possibly more than one actually.

I can implement a quick fix (i.e. patch mc_issue_update() to call relationship_can_resolve_bug() and return a faultBadRequest if not) for now, but to be clean we really need a new **IssueUpdateCommand**... That is a complex beast however, and I don't really have the time to work on this right now.

**Comment by dregad** [comment]
> to be clean we really need a new **IssueUpdateCommand**

Opened [#32861](https://mantisbt.org/bugs/view.php?id=32861) to track this.

**Pull request closed without merging**
