### PR TITLE
Fix hardcoded email titles

### PR DESCRIPTION
**Pull request by dregad**
Regression introduced by 03c5a5d18cfef07dec45a1025072981f24a5f07c.

Fixes [#19984](https://www.mantisbt.org/bugs/view.php?id=19984)

### CODE REVIEW

**Comment by vboctor** [comment]
I thought we were planning to revert the original change, rather than fixing just these calls, is this still the plan?

**Comment by atrol** [comment]
I think it's better this way.

We have this piece of code in bug_api.php
email_generic( $c_bug_id, $t_status, 'email_notification_title_for_status_bug_' . $t_status );
So we should deal the same way with it at other places instead of having an additional function for each status.

**Comment by atrol** [comment]
@dregad, you missed this one
```
email_generic( $t_sponsorship->bug_id, 'sponsor', 'A sponsorship of the following issue was withdrawn.' );
```

**Comment by dregad** [comment]
@vboctor as mentioned in 03c5a5d18cfef07dec45a1025072981f24a5f07c I forgot about that discussion. That being said, I am not opposed to simply reverting, although like Roland I believe it makes sense to reduce the number of API calls.

Since as far as I can remember you never really explained what the *direction of where you would like notifications to go* is, I can't say whether it would be preferable to simply revert Paul's commit, or just merge that PR.

**Comment by vboctor** [comment]
I've submitted a pull request with reverting the original change - see https://github.com/mantisbt/mantisbt/pull/626

The PR has an explanation of the reasons.  Happy to discuss further.

**Comment by dregad** [comment]
Closing this in favor of #626.

**Pull request closed without merging**
