### PR TITLE
Remove $g_debug_email in favor of mailtrap.io

### PR DESCRIPTION
**Pull request by vboctor**
Fixes #21860

### CODE REVIEW

**Comment by atrol** [comment]
👎 
Maybe I don't understand the benefit of it, but wouldn't it mean that
a) I have to pay for mailtrap.io when using MantisBT in a profit organization
b) I depend on a 3rd party external service in the cloud for debugging purposes
c) email contents go over public lines and are visible for the mailtrap.io provider  (I use debug_email when upgrading internal production systems)

Why should we remove a useful feature?
I see mailtrap.io just as an additional option.

**Comment by cproensa** [comment]
:-1:
I the same reasons than @atrol 

This option does not conflicts in any way with using a "trapping" mail server
Additionally, removing this option will make harder to test with off-the -shelf setups, since you now need to have a system that behaves like that site.

> I see mailtrap.io just as an additional option

My debug methodology is:
set debug_email to "user@localhost"
use a mail client to see local mailbox (eg, mutt)


Additionally:
This is **removing**, not deprectaing
Targeted at 1.3?

**Comment by vboctor** [comment]
@cproensa I should have called it "removing" rather than "deprecating".  Can target this to master instead of master-1.3.x. We have removed mail priority from 1.3.x and 2.0.0 at the same time pretty much.  This is also not a runtime feature, but a plugin feature.

For on-box scenarios:

- [MailCatcher](https://github.com/sj26/mailcatcher)
- localhost as per @cproensa approach.  However, without debug email, user will have to set email addresses to localhost email addresses.

I like the idea of using standard production code during debugging.  However, if the team feels we should keep this debugging functionality, I ok as well.

It may be worth documenting the alternatives for testing email, I have seen people struggle with email setup in general both for development and production scenarios.

**Comment by cproensa** [comment]
> I should have called it "removing" rather than "deprecating"

and still, there is no actual implication to mailtrap.io. So the point discussed here should be strictly the removal of the functionality

> It may be worth documenting the alternatives for testing email

sure, thats a good idea 
My approach is quick and dirty, but good enough for me. A plus is that it works with the standards provided by any linux distribution (eg sendmail), and don't need external connectivity.

> I like the idea of using standard production code during debugging. However, if the team feels we should keep this debugging functionality, I ok as well.

you mean, like, or don't like? anyway i don't see much relation. This is not a compiled executable, so it's not like we can easily release without the debugging logic.
So you maybe mean that this debugging option (and others) should not be present in a production instance? That's another whole point, which seems legit. But right now i don't know how that could be done.

**Comment by dregad** [comment]
I find the debug e-mail is very useful and simple to use for behind-the-firewall scenarios.

While mailtrap is a nice tool, I see it as an additional option, not as an exclusive replacement for the debug emails.

**Pull request closed without merging**
