### PR TITLE
Travis builds timing out since merge of GHSA-mcqj-7p29-9528

### PR DESCRIPTION
**Pull request by dregad**

### CODE REVIEW

**Comment by atrol** [comment]
@dregad suspect you have to add now also `path`  to the install.hpp URL.

**Comment by dregad** [comment]
> @dregad suspect you have to add now also `path` to the install.php URL.

That was my first guess too, but I just tried that and it's still not working.

I do not understand why the curl call is not returning any output from the installer.

**Comment by dregad** [comment]
And it's definitely the change to the installer that's breaking it, I just reverted and the build succeeded.

**Comment by dregad** [comment]
Even more strange, I ran the curl command locally and everything worked as expected 😕

**Comment by dregad** [comment]
When setting `path=http://$HOSTNAME:$PORT/` it does not work, maybe some url encoding issue ?

Anyway it works OK with an empty path so let's use that.

**Pull request merged**
