### PR TITLE
Correct list of accepted files for dropzone

### PR DESCRIPTION
**Pull request by atrol**
Fixes #22169

### CODE REVIEW

**Comment by dregad** [comment]
It would be useful to describe the applied correction (i.e. add `.` prefix) in the commit message.

**Comment by atrol** [comment]
Added some more information to commit message.

**Comment by atrol** [comment]
@dregad I am not able to push to master
remote: error: GH006: Protected branch update failed for refs/heads/master

**Comment by dregad** [comment]
@atrol can you please try again now

**Comment by atrol** [comment]
Got no longer error when pushing.

**Comment by dregad** [comment]
I'm not sure I fully understand how this Github branch restriction business really works :confused:

**Pull request merged**
