### PR TITLE
Add tests for utility functions from adm_config_test.php

### PR DESCRIPTION
**Pull request by rombert**
As discussed in PR #131 , I provided basic tests for the utility functions defined in the adm_config_test.php .

Fixes:
- [16931: PHPUnit tests for admin config functions](http://www.mantisbt.org/bugs/view.php?id=16931)
- [16932: PHPUnit tests for admin config functions](http://www.mantisbt.org/bugs/view.php?id=16932)

### CODE REVIEW

**Comment by l266509** [comment]
@vboctor @giallu @daryn @rombert @atrol @grangeway @dregad @Dentxinho @bieli @tomcarlson @syncguru @diegovice @caribe @fager @nikoutel @6RUN0 @AgnidykhBayky @sayyidsh @PixelstreamAU @JohnMS @mikeching @g-taki @benv8nam @stew721 @sayazyi @lezouretalice @SuriyaaKudoIsc @solovets @kacmem @xiaojiangang @chenyongze @myu9882 @markmarco16 @mgretler @lincolnwung @krime @scottmatheina @FavioGalvis @vand3rson @like9729 @badfiles @zenithtekla @SureShinde @netsf @csatwood @miao606 @mdj20130907 @bitlin @ioroid @supertassu @TasCraft @fernandodelucca @ulkuderner @vbathke @hersonpc @jrtorres42 @thejuanwhocode @cyuankai @mantianxingxing @shirleycharlin @boby75 @Lordshell @BurningWind @jaguarxii @Praymundo @johnzastrow @ewmartinez @marcioklein @lypzln @nospam1961 @jllano @lincoln56 @modir @xiaocnie @sivpro @planetbrett @teodortalov @ltpgt @pbcreativesolutions @Gantha @Gerolkae @gunsmoker @nikerabbit @translatewiki  Whats status of this PR?

**Comment by vboctor** [comment]
Closing due to lack of activity and focus on working on the REST API.

**Comment by dregad** [comment]
I also don't understand your point about focusing on REST API - this has nothing to do with it.

I believe the changes in this PR are still a valid code cleanup, not to mention the fact that PHPUnit tests improvements are always good.

I short, I disagree with closure, unless this is tracked elsewhere (I don't see an issue reference in the PR, and did not search for one in the tracker).

**Comment by dregad** [comment]
Actually, I just looked at this over lunch, and it was actually fixed in #761 when I refactored the regex-based parser using the PHP Tokenizer.

**Pull request closed without merging**
